import type { Meta, StoryObj } from '@storybook/react-vite'
import type { ReactNode } from 'react'
import {
  Accessibility,
  AlertOctagon,
  AlertTriangle,
  Bell,
  CalendarDays,
  CheckCircle2,
  CircleUserRound,
  Download,
  FileClock,
  Gauge,
  Goal,
  Languages,
  LifeBuoy,
  LockKeyhole,
  LogOut,
  Ruler,
  Settings2,
  ShieldCheck,
  Trash2,
  WalletCards,
} from 'lucide-react'
import { momentumEvidence } from './coverage'
import {
  ChartBars,
  localeFromStory,
  ProductFrame,
  SpecBadge,
  SpecButton,
  SpecCallout,
  SpecCard,
  SpecField,
  SpecHeader,
  SpecList,
  SpecMetric,
  SpecOverlay,
  SpecProgress,
  SpecSelect,
  SpecTable,
  tx,
  type SpecLocale,
} from './ProductSpec'

type ProgressView = 'overview' | 'text' | 'table' | 'empty' | 'normal' | 'caution' | 'referral'
type AccountSection = 'overview' | 'profile' | 'measurements' | 'preferences' | 'language' | 'notifications' | 'accessibility' | 'subscription' | 'history' | 'data' | 'delete' | 'help' | 'signout'

function ProgressScreen({ locale, view }: { locale: SpecLocale; view: ProgressView }) {
  if (view === 'empty') {
    return <ProductFrame active="progress" locale={locale} title={tx(locale, 'پیشرفت', 'Progress')}><SpecHeader body={tx(locale, 'روندها بعد از چند روز ثبت تمرین یا وعده دیده می‌شوند. گزارش هفتگی از همین‌جا شروع می‌شود.', 'Trends appear after a few logged workouts or meals. The weekly report starts here.')} eyebrow={tx(locale, 'شروع مسیر', 'Getting started')} title={tx(locale, 'هنوز داده‌ای ثبت نشده', 'No progress data yet')} /><SpecCard className="is-wide mo-spec__weekly-cta" tone="brand"><SpecBadge tone="brand">{tx(locale, 'گزارش هفته', 'Weekly report')}</SpecBadge><h2>{tx(locale, 'اولین گزارش هفتگی را ثبت کن', 'Save your first weekly report')}</h2><p>{tx(locale, 'اختیاری است، اما اینجا مسیر اصلی پیشرفت است. هوش مصنوعی صدا زده نمی‌شود.', 'It is optional, but this is the main Progress action. No AI is called.')}</p><SpecButton>{tx(locale, 'شروع گزارش هفتگی', 'Start weekly report')}</SpecButton></SpecCard></ProductFrame>
  }

  if (view === 'normal' || view === 'caution' || view === 'referral') return <CheckInOutcome locale={locale} outcome={view} />

  return (
    <ProductFrame active="progress" locale={locale} title={tx(locale, 'پیشرفت', 'Progress')}>
      <SpecHeader aside={<SpecBadge tone="success">{tx(locale, 'هفته ۳ از ۵', 'Week 3 of 5')}</SpecBadge>} body={tx(locale, 'پیشرفت، روند است نه نمره. جدول و خلاصه متنی همان اطلاعات نمودار را منتقل می‌کنند.', 'Progress is a trend, not a grade. The table and text summary carry the same information as the chart.')} eyebrow={tx(locale, 'دوره جاری', 'Current period')} title={tx(locale, 'روند برنامه ماهانه', 'Monthly plan trend')} />
      {view === 'overview' ? <Overview locale={locale} /> : null}
      {view === 'text' ? <TextAlternative locale={locale} /> : null}
      {view === 'table' ? <TableAlternative locale={locale} /> : null}
    </ProductFrame>
  )
}

function ProgressOfflineView({ locale }: { locale: SpecLocale }) {
  return <ProductFrame active="progress" locale={locale} title={tx(locale, 'پیشرفت', 'Progress')}><SpecHeader eyebrow={tx(locale, 'نسخه ذخیره‌شده', 'Saved summary')} title={tx(locale, 'روند تا هفته سوم در دسترس است', 'Progress through week three is available')} body={tx(locale, 'این خلاصه تا ۶ شهریور ۱۴۰۵ را پوشش می‌دهد و تا اتصال دوباره فقط‌خواندنی است.', 'This summary covers data through Aug 28, 2026 and remains read-only until reconnection.')} /><SpecCallout icon={<AlertTriangle />} title={tx(locale, 'داده هفته جاری ممکن است کامل نباشد', 'Current-week data may be incomplete')} tone="warning">{tx(locale, 'آخرین همگام‌سازی: امروز، ۰۸:۴۲', 'Last synced today at 08:42')}</SpecCallout><div style={{ marginBlockStart: '1rem' }}><Overview locale={locale} /></div></ProductFrame>
}

function WeeklyCheckInForm({ locale }: { locale: SpecLocale }) {
  return <ProductFrame active="progress" locale={locale} title={tx(locale, 'گزارش هفتگی', 'Weekly report')}><SpecHeader eyebrow={tx(locale, 'پایان هفته سوم', 'End of week three')} title={tx(locale, 'گزارش این هفته', 'This week’s report')} body={tx(locale, 'اختیاری است، اما این ورودی اصلی پیشرفت است. ذخیره می‌شود؛ هوش مصنوعی صدا زده نمی‌شود و برنامه این ماه عوض نمی‌شود.', 'Optional, but this is the main Progress input. It is saved; no AI is called and this month’s plan does not change.')} /><SpecCard className="mo-spec__weekly-cta" tone="brand"><div className="mo-spec__form-grid"><SpecSelect label={tx(locale, 'پایبندی به تمرین', 'Workout adherence')} value={tx(locale, '۳ از ۳ جلسه', '3 of 3 sessions')} /><SpecSelect label={tx(locale, 'پایبندی به تغذیه', 'Nutrition adherence')} value={tx(locale, 'بیشتر روزها', 'Most days')} /><SpecSelect label={tx(locale, 'انرژی کلی', 'Overall energy')} value={tx(locale, '۷ از ۱۰', '7 of 10')} /><SpecSelect label={tx(locale, 'بازیابی', 'Recovery')} value={tx(locale, 'خوب', 'Good')} /></div><SpecField hint={tx(locale, 'اختیاری', 'Optional')} label={tx(locale, 'یادداشت', 'Note')} multiline value={tx(locale, 'زمان عصر برای تمرین بهتر بود.', 'Evening workouts worked better.')} /><div className="mo-spec__actions"><SpecButton>{tx(locale, 'ثبت گزارش هفتگی', 'Save weekly report')}</SpecButton></div></SpecCard></ProductFrame>
}

function NextCycleReadiness({ locale }: { locale: SpecLocale }) {
  return <ProductFrame active="progress" locale={locale} title={tx(locale, 'پایان ماه هدیه', 'Gift month ending')}><SpecHeader eyebrow={tx(locale, 'بعد از گزارش هفته آخر', 'After the last weekly report')} title={tx(locale, 'ماه رایگان تمام می‌شود؛ برنامه بعد با عضویت ساخته می‌شود', 'The free month is ending; the next plan needs membership')} body={tx(locale, 'گزارش هفته آخر ذخیره شد. از اینجا می‌فهمی ماه بعد چیست. بیشتر افراد از هدیه برنامه اول به همین نقطه می‌رسند.', 'The last weekly report is saved. This is where you see what happens next. Most people reach this point from the first-plan gift.')} /><div className="mo-spec__grid"><SpecCard className="is-wide" tone="brand"><SpecBadge tone="brand">{tx(locale, 'هدیه ماه اول استفاده شد', 'First-month gift used')}</SpecBadge><h2>{tx(locale, 'برای ماه بعد عضویت را شروع کن', 'Start membership for next month')}</h2><p>{tx(locale, 'قیمت نهایی پیش از شارژ دیده می‌شود. کارت تا ساخت برنامه ماه بعد شارژ می‌شود.', 'Final price is shown before any charge. The card is charged when the next month’s plan is created.')}</p><div className="mo-spec__actions"><SpecButton>{tx(locale, 'شروع عضویت', 'Start membership')}</SpecButton><SpecButton kind="secondary">{tx(locale, 'بعداً تصمیم می‌گیرم', 'Decide later')}</SpecButton></div></SpecCard><SpecCard><SpecField hint={tx(locale, 'اختیاری · حداکثر ۵۰۰ نویسه', 'Optional · 500 characters max')} label={tx(locale, 'یادداشت برای ماه بعد', 'Note for next month')} multiline value="" /><SpecButton kind="secondary">{tx(locale, 'ذخیره یادداشت', 'Save note')}</SpecButton></SpecCard></div></ProductFrame>
}

function Overview({ locale }: { locale: SpecLocale }) {
  return <div className="mo-spec__stack"><SpecCard className="is-wide mo-spec__weekly-cta" tone="brand"><div className="mo-spec__heading" style={{ marginBlockEnd: '1rem' }}><div><SpecBadge tone="brand">{tx(locale, 'گزارش هفته', 'Weekly report')}</SpecBadge><h2>{tx(locale, 'گزارش هفته سوم آماده است', 'Week-three report is ready')}</h2><p>{tx(locale, 'اختیاری است، اما این کارت مسیر اصلی پیشرفت است.', 'Optional, but this card is the main Progress action.')}</p></div></div><SpecButton>{tx(locale, 'ثبت گزارش هفتگی', 'Save weekly report')}</SpecButton></SpecCard><div className="mo-spec__grid"><SpecMetric detail={tx(locale, 'هدف: ۳ جلسه', 'Goal: 3 sessions')} label={tx(locale, 'تمرین این هفته', 'Training this week')} tone="success" value={tx(locale, '۳ / ۳', '3 / 3')} /><SpecMetric detail={tx(locale, '۱٫۲ کیلوگرم از شروع', '1.2 kg from start')} label={tx(locale, 'تغییر وزن', 'Weight change')} value={locale === 'fa' ? '۱٫۲− کیلوگرم' : '−1.2 kg'} /><SpecMetric detail={tx(locale, 'میانگین ۷ روز', '7-day average')} label={tx(locale, 'انرژی', 'Energy')} tone="energy" value={tx(locale, '۷٫۴ / ۱۰', '7.4 / 10')} /></div><SpecCard><div className="mo-spec__heading" style={{ marginBlockEnd: '1rem' }}><div><h2>{tx(locale, 'پایبندی هفتگی', 'Weekly adherence')}</h2><p>{tx(locale, 'درصد فعالیت‌های برنامه‌ریزی‌شده که ثبت شده‌اند', 'Percentage of planned activities logged')}</p></div><SpecBadge tone="brand">{tx(locale, '۸۶٪', '86%')}</SpecBadge></div><ChartBars labels={locale === 'fa' ? ['هفته ۱', 'هفته ۲', 'هفته ۳', 'هفته ۴'] : ['Week 1', 'Week 2', 'Week 3', 'Week 4']} values={[62, 78, 86, 18]} /></SpecCard><div className="mo-spec__actions"><SpecButton kind="secondary">{tx(locale, 'خلاصه متنی نمودار', 'Text chart summary')}</SpecButton><SpecButton kind="secondary">{tx(locale, 'نمایش جدول', 'View data table')}</SpecButton></div></div>
}

function TextAlternative({ locale }: { locale: SpecLocale }) {
  return <SpecCard><SpecBadge tone="info">{tx(locale, 'جایگزین دسترس‌پذیر نمودار', 'Accessible chart alternative')}</SpecBadge><h2>{tx(locale, 'خلاصه کامل همان چهار مقدار', 'Complete summary of the same four values')}</h2><p>{tx(locale, 'پایبندی هفته اول ۶۲٪، هفته دوم ۷۸٪، هفته سوم ۸۶٪ و هفته چهارم تا امروز ۱۸٪ است. مقدار ۱۸٪ ناقص است چون هفته چهارم هنوز ادامه دارد و حذف یا به‌صورت صفر تفسیر نمی‌شود.', 'Adherence is 62% in week one, 78% in week two, 86% in week three, and 18% so far in week four. The 18% value is partial because week four is still in progress; it is neither omitted nor interpreted as zero.')}</p><SpecCallout icon={<CheckCircle2 />} title={tx(locale, 'سه هفته کامل رو به بهبودند', 'The three complete weeks are improving')} tone="success">{tx(locale, 'هفته چهارم باید بعد از کامل‌شدن با هفته‌های قبل مقایسه شود.', 'Week four should be compared only after it is complete.')}</SpecCallout><div className="mo-spec__actions"><SpecButton kind="secondary">{tx(locale, 'بازگشت به نمودار', 'Back to chart')}</SpecButton></div></SpecCard>
}

function TableAlternative({ locale }: { locale: SpecLocale }) {
  return <div className="mo-spec__stack"><SpecCallout icon={<Accessibility />} title={tx(locale, 'این جدول دقیقاً همان داده نمودار را دارد', 'This table contains exactly the chart data')} tone="info">{tx(locale, 'وضعیت ناقص هفته چهارم در کنار مقدار ۱۸٪ مشخص شده است.', 'Week four is marked partial alongside its 18% value.')}</SpecCallout><SpecTable columns={locale === 'fa' ? ['هفته', 'تمرین', 'وعده‌ها', 'انرژی', 'پایبندی'] : ['Week', 'Workouts', 'Meals', 'Energy', 'Adherence']} rows={locale === 'fa' ? [['هفته ۱', '۲ از ۳', '۲۱ از ۲۸', '۶٫۸', '۶۲٪'], ['هفته ۲', '۳ از ۳', '۲۳ از ۲۸', '۷٫۱', '۷۸٪'], ['هفته ۳', '۳ از ۳', '۲۵ از ۲۸', '۷٫۴', '۸۶٪'], ['هفته ۴ · ناقص', '۱ از ۳', '۵ از ۲۸', '۷٫۰', '۱۸٪']] : [['Week 1', '2 of 3', '21 of 28', '6.8', '62%'], ['Week 2', '3 of 3', '23 of 28', '7.1', '78%'], ['Week 3', '3 of 3', '25 of 28', '7.4', '86%'], ['Week 4 · partial', '1 of 3', '5 of 28', '7.0', '18%']]} /></div>
}

function CheckInOutcome({ locale, outcome }: { locale: SpecLocale; outcome: 'normal' | 'caution' | 'referral' }) {
  const data = {
    normal: { tone: 'success' as const, icon: <CheckCircle2 />, title: tx(locale, 'روندت پایدار است', 'Your trend is steady'), body: tx(locale, 'انرژی و ریکاوری در محدوده معمول تو هستند. برنامه فعلی بدون تغییر ادامه پیدا می‌کند.', 'Energy and recovery are within your usual range. Your current plan continues unchanged.'), action: tx(locale, 'بازگشت به امروز', 'Back to Today') },
    caution: { tone: 'warning' as const, icon: <AlertTriangle />, title: tx(locale, 'این هفته کمی سبک‌تر پیش برو', 'Take it a little easier this week'), body: tx(locale, 'خواب و انرژی سه روز متوالی پایین‌تر از روند معمول بوده‌اند. شدت تمرین امروز کاهش داده می‌شود.', 'Sleep and energy have been below your usual trend for three days. Today’s workout intensity is reduced.'), action: tx(locale, 'دیدن برنامه تنظیم‌شده', 'View adjusted session') },
    referral: { tone: 'warning' as const, icon: <AlertOctagon />, title: tx(locale, 'پیش از ادامه با یک متخصص صحبت کن', 'Talk with a qualified professional before continuing'), body: tx(locale, 'الگوی چند هفته اخیر خارج از محدوده معمول توست، اما این وضعیت به‌عنوان فوریت پزشکی نمایش داده نمی‌شود. برای ارزیابی مناسب با متخصص سلامت دارای صلاحیت تماس بگیر.', 'Your recent multi-week pattern is outside your usual range, but this state is not presented as a medical emergency. Contact a qualified health professional for appropriate assessment.'), action: tx(locale, 'دیدن راهنمای مراجعه', 'View professional-referral guidance') },
  }
  const item = data[outcome]
  return <ProductFrame active="progress" locale={locale} title={tx(locale, 'نتیجه بررسی هفتگی', 'Weekly check-in result')}><SpecHeader eyebrow={tx(locale, 'نتیجه', 'Result')} title={item.title} body={item.body} /><SpecCard className="mo-spec__state-card"><span className={`mo-spec__state-icon mo-spec__state-icon--${item.tone}`}>{item.icon}</span><SpecCallout title={outcome === 'referral' ? tx(locale, 'این تشخیص یا وضعیت فوری نیست', 'This is not a diagnosis or emergency state') : tx(locale, 'تأثیر روی برنامه', 'Plan impact')} tone={item.tone}>{outcome === 'normal' ? tx(locale, 'هیچ تغییر خودکاری برای دوره جاری انجام نمی‌شود.', 'No automatic change is made to the current period.') : outcome === 'caution' ? tx(locale, 'گزارش ذخیره شد. برنامه ماه بازتولید نمی‌شود.', 'The report is saved. The monthly plan is not regenerated.') : tx(locale, 'تا دریافت راهنمایی حرفه‌ای، تمرین پرفشار پیشنهاد نمی‌شود و برنامه ماهانه بازتولید نمی‌شود.', 'High-intensity activity is not recommended until you receive professional guidance; the monthly plan is not regenerated.')}</SpecCallout><div className="mo-spec__actions"><SpecButton>{item.action}</SpecButton><SpecButton kind="secondary">{tx(locale, 'بازگشت به پیشرفت', 'Back to Progress')}</SpecButton></div></SpecCard></ProductFrame>
}

const accountCopy: Record<AccountSection, { icon: typeof Settings2; fa: string; en: string; bodyFa: string; bodyEn: string }> = {
  overview: { icon: CircleUserRound, fa: 'حساب و تنظیمات', en: 'Account & settings', bodyFa: 'اطلاعات شخصی، ترجیحات، عضویت و داده‌ها را مدیریت کن.', bodyEn: 'Manage personal details, preferences, membership, and data.' },
  profile: { icon: Goal, fa: 'پروفایل و هدف‌ها', en: 'Profile & goals', bodyFa: 'اطلاعات پایه و هدف اصلی دوره بعد', bodyEn: 'Personal details and the primary goal for the next period' },
  measurements: { icon: Ruler, fa: 'اندازه‌گیری‌ها', en: 'Measurements', bodyFa: 'تاریخچه وزن و اندازه‌ها با امکان ثبت دستی', bodyEn: 'Weight and measurement history with manual entry' },
  preferences: { icon: Settings2, fa: 'ترجیحات برنامه', en: 'Plan preferences', bodyFa: 'تغییرهایی که در درخواست دوره بعد استفاده می‌شوند', bodyEn: 'Changes used in the next period request' },
  language: { icon: Languages, fa: 'زبان، تقویم و واحدها', en: 'Language, calendar & units', bodyFa: 'زبان قابل تغییر است؛ کشور فقط مسیر پرداخت را تعیین می‌کند', bodyEn: 'Language is editable; country only routes payment' },
  notifications: { icon: Bell, fa: 'اعلان‌ها', en: 'Notifications', bodyFa: 'یادآوری‌ها و وضعیت آماده‌شدن برنامه', bodyEn: 'Reminders and plan-ready updates' },
  accessibility: { icon: Accessibility, fa: 'دسترس‌پذیری', en: 'Accessibility', bodyFa: 'حرکت کمتر، شفافیت کمتر و متن خواناتر', bodyEn: 'Reduced motion, reduced transparency, and readable text' },
  subscription: { icon: WalletCards, fa: 'عضویت', en: 'Membership', bodyFa: 'یک اشتراک Momentum و وضعیت تمدید', bodyEn: 'One Momentum membership and renewal status' },
  history: { icon: FileClock, fa: 'تاریخچه برنامه‌ها', en: 'Plan history', bodyFa: 'دوره‌های قبلی فقط‌خواندنی و قابل مشاهده', bodyEn: 'Past periods remain visible and read-only' },
  data: { icon: Download, fa: 'دریافت داده‌ها', en: 'Download your data', bodyFa: 'درخواست نسخه قابل حمل از داده‌های حساب', bodyEn: 'Request a portable copy of account data' },
  delete: { icon: Trash2, fa: 'حذف حساب', en: 'Delete account', bodyFa: 'فرایند آگاهانه با تأیید نهایی و حذف دائمی', bodyEn: 'An informed flow with final confirmation and permanent deletion' },
  help: { icon: LifeBuoy, fa: 'راهنما، ایمنی و قوانین', en: 'Help, safety & legal', bodyFa: 'پشتیبانی، راهنمای سلامت و اسناد حقوقی', bodyEn: 'Support, health guidance, and legal documents' },
  signout: { icon: LogOut, fa: 'خروج امن', en: 'Secure sign out', bodyFa: 'داده‌های همگام‌شده در حساب باقی می‌مانند', bodyEn: 'Synced data remains safely in your account' },
}

function AccountScreen({ locale, section }: { locale: SpecLocale; section: AccountSection }) {
  const item = accountCopy[section]
  const Icon = item.icon
  return <ProductFrame active="me" locale={locale} title={tx(locale, 'من', 'Me')}><SpecHeader eyebrow={tx(locale, 'حساب Momentum', 'Momentum account')} title={tx(locale, item.fa, item.en)} body={tx(locale, item.bodyFa, item.bodyEn)} /><AccountContent locale={locale} section={section} icon={<Icon />} /></ProductFrame>
}

function AccountContent({ locale, section, icon }: { locale: SpecLocale; section: AccountSection; icon: ReactNode }) {
  if (section === 'overview') return <SpecList rows={(['profile', 'measurements', 'preferences', 'language', 'notifications', 'accessibility', 'subscription', 'history', 'data', 'help', 'delete', 'signout'] as AccountSection[]).map((key) => ({ icon: (() => { const I = accountCopy[key].icon; return <I /> })(), tone: key === 'subscription' ? 'brand' : key === 'delete' ? 'danger' : 'neutral', label: tx(locale, accountCopy[key].fa, accountCopy[key].en), detail: tx(locale, accountCopy[key].bodyFa, accountCopy[key].bodyEn), value: '›' }))} />
  if (section === 'profile') return <SpecCard><div className="mo-spec__form-grid"><SpecField label={tx(locale, 'نام', 'Name')} value={tx(locale, 'سارا', 'Sara')} /><SpecField label={tx(locale, 'تاریخ تولد', 'Date of birth')} value={locale === 'fa' ? '۲۸ اردیبهشت ۱۳۷۱' : 'May 18, 1992'} /><SpecSelect label={tx(locale, 'هدف اصلی', 'Primary goal')} value={tx(locale, 'کاهش چربی همراه حفظ قدرت', 'Fat loss while retaining strength')} /><SpecField label={tx(locale, 'وزن هدف', 'Target weight')} value={locale === 'fa' ? '۶۴ کیلوگرم' : '64 kg'} /></div><div className="mo-spec__actions"><SpecButton>{tx(locale, 'ذخیره تغییرها', 'Save changes')}</SpecButton></div></SpecCard>
  if (section === 'measurements') return <div className="mo-spec__grid"><SpecMetric detail={tx(locale, 'آخرین ثبت: امروز', 'Last logged today')} label={tx(locale, 'وزن فعلی', 'Current weight')} value={locale === 'fa' ? '۷۱٫۲ کیلوگرم' : '71.2 kg'} /><SpecMetric detail={tx(locale, 'از آغاز دوره', 'Since period start')} label={tx(locale, 'تغییر', 'Change')} tone="success" value={locale === 'fa' ? '۱٫۲− کیلوگرم' : '−1.2 kg'} /><SpecCard><SpecButton>{tx(locale, 'ثبت اندازه جدید', 'Add measurement')}</SpecButton></SpecCard><SpecCard className="is-full"><SpecTable columns={locale === 'fa' ? ['تاریخ', 'وزن', 'دور کمر', 'یادداشت'] : ['Date', 'Weight', 'Waist', 'Note']} rows={locale === 'fa' ? [['۲۳ مرداد', '۷۲٫۴', '۸۴ سانتی‌متر', 'شروع دوره'], ['۳۰ مرداد', '۷۱٫۸', '۸۳٫۵ سانتی‌متر', '—'], ['۶ شهریور', '۷۱٫۲', '۸۳ سانتی‌متر', 'انرژی بهتر']] : [['Aug 14', '72.4 kg', '84 cm', 'Period start'], ['Aug 21', '71.8 kg', '83.5 cm', '—'], ['Aug 28', '71.2 kg', '83 cm', 'More energy']]} /></SpecCard></div>
  if (section === 'preferences') return <SpecCard><SpecCallout icon={<CalendarDays />} title={tx(locale, 'این تغییرها برای دوره بعد هستند', 'These changes apply to the next period')} tone="brand">{tx(locale, 'برنامه جاری بازتولید نمی‌شود و درخواست اضافه‌ای مصرف نخواهد شد.', 'The current plan is not regenerated and no extra request is consumed.')}</SpecCallout><div className="mo-spec__form-grid" style={{ marginBlockStart: '1rem' }}><SpecField label={tx(locale, 'تغییر در زمان‌بندی', 'Schedule changes')} multiline value={tx(locale, 'از ماه بعد فقط عصرها امکان تمرین دارم.', 'Next month I can only train in the evenings.')} /><SpecField label={tx(locale, 'تغییر در غذا یا امکانات', 'Food or equipment changes')} multiline value={tx(locale, 'دمبل جدید تا ۲۰ کیلوگرم اضافه شده است.', 'I now have dumbbells up to 20 kg.')} /></div><div className="mo-spec__actions"><SpecButton>{tx(locale, 'ذخیره برای دوره بعد', 'Save for next period')}</SpecButton></div></SpecCard>
  if (section === 'language') return <div className="mo-spec__grid"><SpecCard><h2>{tx(locale, 'زبان و پرداخت', 'Language & payment')}</h2><SpecSelect label={tx(locale, 'زبان برنامه', 'App language')} value={tx(locale, 'فارسی', 'English')} /><SpecField hint={tx(locale, 'کشور فقط درگاه و ارز را تعیین می‌کند', 'Country only selects gateway and currency')} label={tx(locale, 'مسیر پرداخت', 'Payment route')} value={tx(locale, 'ایران · درگاه ایرانی و تومان', 'International · Stripe and USD')} /></SpecCard><SpecCard><h2>{tx(locale, 'ظاهر برنامه', 'Appearance')}</h2><SpecSelect label={tx(locale, 'نمایش', 'Theme')} value={tx(locale, 'روشن', 'Light')} /><p>{tx(locale, 'روشن، تیره یا پیروی از دستگاه؛ هیچ حالت رنگی جداگانه‌ای لازم نیست.', 'Choose Light, Dark, or Follow device; no separate color mode is required.')}</p></SpecCard><SpecCard><h2>{tx(locale, 'تقویم و واحدها', 'Calendar & units')}</h2><SpecSelect label={tx(locale, 'نمایش تاریخ', 'Date display')} value={tx(locale, 'هجری شمسی', 'Gregorian')} /><SpecSelect label={tx(locale, 'آغاز هفته', 'First day of week')} value={tx(locale, 'شنبه', 'Monday')} /><SpecSelect label={tx(locale, 'وزن و قد', 'Weight & height')} value={tx(locale, 'کیلوگرم · سانتی‌متر', 'Kilograms · centimetres')} /></SpecCard></div>
  if (section === 'notifications') return <div className="mo-spec__stack"><SpecCallout icon={<Bell />} title={tx(locale, 'اجازه اعلان در مرورگر رد شده است', 'Browser notification permission is denied')} tone="warning">{tx(locale, 'انتخاب کانال‌ها حفظ شده، اما اعلان دستگاه تا فعال‌کردن مجوز در تنظیمات مرورگر ارسال نمی‌شود.', 'Channel choices are preserved, but device notifications cannot be delivered until permission is enabled in browser settings.')}</SpecCallout><div className="mo-spec__actions"><SpecButton kind="secondary">{tx(locale, 'بازکردن راهنمای تنظیمات دستگاه', 'Open device-settings guidance')}</SpecButton><SpecButton kind="secondary">{tx(locale, 'بررسی دوباره مجوز', 'Check permission again')}</SpecButton></div><SpecList rows={[{ icon: <Bell />, tone: 'brand', label: tx(locale, 'آماده‌شدن برنامه', 'Plan ready'), detail: tx(locale, 'اعلان پس از ورود موفق برنامه', 'After successful plan import'), value: tx(locale, 'روشن · مسدود', 'On · blocked') }, { icon: <CalendarDays />, tone: 'brand', label: tx(locale, 'گزارش هفتگی', 'Weekly report'), detail: tx(locale, 'پایان هر هفته', 'End of each week'), value: tx(locale, 'روشن · مسدود', 'On · blocked') }, { icon: <CalendarDays />, label: tx(locale, 'یادآوری تمرین', 'Workout reminder'), detail: tx(locale, '۲ ساعت پیش از زمان انتخابی', '2 hours before the selected time'), value: tx(locale, 'روشن · مسدود', 'On · blocked') }, { icon: <Gauge />, label: tx(locale, 'بررسی روزانه', 'Daily check-in'), detail: tx(locale, 'اختیاری', 'Optional'), value: tx(locale, 'خاموش', 'Off') }]} /></div>
  if (section === 'accessibility') return <SpecCard><SpecList rows={[{ icon: <Accessibility />, tone: 'brand', label: tx(locale, 'حرکت کمتر', 'Reduce motion'), detail: tx(locale, 'انیمیشن‌های غیرضروری حذف می‌شوند', 'Nonessential animation is removed'), value: tx(locale, 'پیروی از دستگاه', 'Follow device') }, { icon: <ShieldCheck />, label: tx(locale, 'شفافیت کمتر', 'Reduce transparency'), detail: tx(locale, 'لایه‌های شیشه‌ای با سطح مات جایگزین می‌شوند', 'Glass chrome uses its opaque fallback'), value: tx(locale, 'پیروی از دستگاه', 'Follow device') }, { icon: <Languages />, label: tx(locale, 'متن بزرگ‌تر', 'Larger text'), detail: tx(locale, 'چیدمان تا ۲۰۰٪ بدون حذف محتوا سازگار است', 'Layout reflows up to 200% without losing content'), value: tx(locale, 'استاندارد', 'Default') }]} /></SpecCard>
  if (section === 'subscription') return <div className="mo-spec__grid"><SpecCard className="is-wide" tone="brand"><SpecBadge tone="success">{tx(locale, 'فعال', 'Active')}</SpecBadge><h2>{tx(locale, 'عضویت Momentum', 'Momentum membership')}</h2><p>{tx(locale, 'تمدید بعدی: ۲۲ شهریور ۱۴۰۵ · مبلغ به ریال ایران', 'Renews Sep 13, 2026 · price in US dollars')}</p><SpecProgress label={tx(locale, 'دوره برنامه', 'Plan period')} value={64} /><div className="mo-spec__actions"><SpecButton kind="secondary">{tx(locale, 'مدیریت پرداخت', 'Manage billing')}</SpecButton><SpecButton kind="secondary">{tx(locale, 'لغو تمدید آینده', 'Cancel future renewal')}</SpecButton></div><SpecCallout icon={<AlertTriangle />} title={tx(locale, 'پس از لغو چه می‌شود؟', 'What happens after cancellation?')} tone="warning">{tx(locale, 'عضویت تا ۲۲ شهریور فعال می‌ماند؛ تاریخچه خواندنی است و فقط ساخت دوره بعد متوقف می‌شود. پیش از تأیید نهایی می‌توانی انصراف بدهی.', 'Membership stays active through Sep 13; history remains readable and only the next plan is blocked. You can back out before final confirmation.')}</SpecCallout></SpecCard><SpecCard><h2>{tx(locale, 'درخواست دوره', 'Period request')}</h2><SpecBadge tone="neutral">{tx(locale, '۱ از ۱ استفاده شده', '1 of 1 used')}</SpecBadge><p>{tx(locale, 'درخواست بعدی بعد از پایان این دوره و فقط با عضویت فعال باز می‌شود.', 'The next request unlocks after this period ends and only with active membership.')}</p></SpecCard></div>
  if (section === 'history') return <SpecList rows={[{ icon: <FileClock />, tone: 'brand', label: tx(locale, 'دوره ۱ · جاری', 'Period 1 · Current'), detail: tx(locale, '۲۳ مرداد تا ۲۲ شهریور ۱۴۰۵', 'Aug 14 – Sep 13, 2026'), value: tx(locale, 'فعال', 'Active') }, { icon: <FileClock />, label: tx(locale, 'برنامه پایه پیش‌نمایش', 'Initial preview'), detail: tx(locale, 'نسخه قبل از عضویت · فقط‌خواندنی', 'Before membership · read-only'), value: tx(locale, 'مشاهده', 'View') }]} />
  if (section === 'data') return <div className="mo-spec__grid"><SpecCard className="is-wide"><span className="mo-spec__state-icon mo-spec__state-icon--info">{icon}</span><h2>{tx(locale, 'درخواست دریافت داده', 'Request your data')}</h2><p>{tx(locale, 'فایل شامل پروفایل، پاسخ‌های راه‌اندازی، برنامه‌ها و ثبت‌های پیشرفت است. آماده‌سازی ممکن است تا ۲۴ ساعت طول بکشد.', 'The archive includes profile, onboarding answers, plans, and progress entries. Preparation can take up to 24 hours.')}</p><SpecButton>{tx(locale, 'درخواست فایل', 'Request archive')}</SpecButton></SpecCard><SpecCard><SpecBadge tone="info">{tx(locale, 'در انتظار آماده‌سازی', 'Pending')}</SpecBadge><h2>{tx(locale, 'درخواست EX-204', 'Request EX-204')}</h2><p>{tx(locale, 'ثبت: امروز ۰۹:۱۵ · اعلان پس از آماده‌شدن', 'Requested today at 09:15 · notification when ready')}</p></SpecCard><SpecCard><SpecBadge tone="success">{tx(locale, 'آماده دریافت', 'Ready')}</SpecBadge><h2>{tx(locale, 'لینک تا ۲۴ ساعت معتبر است', 'Link valid for 24 hours')}</h2><SpecButton>{tx(locale, 'دریافت فایل رمزگذاری‌شده', 'Download encrypted archive')}</SpecButton></SpecCard><SpecCard><SpecBadge tone="neutral">{tx(locale, 'منقضی شده', 'Expired')}</SpecBadge><p>{tx(locale, 'لینک قبلی دیگر کار نمی‌کند؛ درخواست تازه داده تکراری ایجاد نمی‌کند.', 'The old link no longer works; a new request does not duplicate account data.')}</p><SpecButton kind="secondary">{tx(locale, 'ساخت لینک تازه', 'Create a new link')}</SpecButton></SpecCard><SpecCard><SpecBadge tone="danger">{tx(locale, 'ناموفق', 'Failed')}</SpecBadge><p>{tx(locale, 'کد EX-ERR-17 · هیچ داده‌ای حذف نشده است.', 'Reference EX-ERR-17 · no account data was deleted.')}</p><SpecButton kind="secondary">{tx(locale, 'تلاش دوباره', 'Try again')}</SpecButton></SpecCard></div>
  if (section === 'delete') return <div className="mo-spec__grid"><SpecCard className="is-wide"><span className="mo-spec__state-icon mo-spec__state-icon--danger">{icon}</span><h2>{tx(locale, 'حذف حساب دائمی و برگشت‌ناپذیر است', 'Account deletion is permanent and cannot be undone')}</h2><p>{tx(locale, 'عضویت لغو می‌شود و داده‌ها طبق سیاست نگه‌داری برای حذف دائمی صف می‌شوند. ابتدا می‌توانی نسخه داده‌ها را دریافت کنی.', 'Membership is cancelled and data is queued for permanent deletion under the retention policy. You can export a copy first.')}</p><SpecField label={tx(locale, 'برای تأیید «حذف دائمی حساب» را بنویس', 'Type “permanently delete account” to confirm')} value="" /><div className="mo-spec__actions"><SpecButton kind="secondary">{tx(locale, 'انصراف', 'Cancel')}</SpecButton><SpecButton disabled kind="danger">{tx(locale, 'حذف دائمی حساب', 'Permanently delete account')}</SpecButton></div></SpecCard><SpecCard><SpecBadge tone="warning">{tx(locale, 'در انتظار حذف', 'Deletion pending')}</SpecBadge><p>{tx(locale, 'درخواست DEL-481 ثبت شده و ورود جدید مسدود است.', 'Request DEL-481 is recorded and new sign-in is blocked.')}</p></SpecCard><SpecCard><SpecBadge tone="success">{tx(locale, 'حذف کامل شد', 'Deletion complete')}</SpecBadge><p>{tx(locale, 'حساب دیگر قابل ورود یا بازیابی نیست.', 'The account can no longer be accessed or recovered.')}</p></SpecCard><SpecCard><SpecBadge tone="danger">{tx(locale, 'حذف کامل نشد', 'Deletion failed')}</SpecBadge><p>{tx(locale, 'حساب حذف نشده و برای بررسی امن قفل مانده است. کد DEL-ERR-09 را به پشتیبانی بده.', 'The account was not deleted and remains safely locked for review. Give support reference DEL-ERR-09.')}</p><SpecButton kind="secondary">{tx(locale, 'تماس با پشتیبانی', 'Contact support')}</SpecButton></SpecCard></div>
  if (section === 'help') return <SpecList rows={[{ icon: <LifeBuoy />, tone: 'info', label: tx(locale, 'پشتیبانی', 'Support'), detail: tx(locale, 'پاسخ به پرسش‌های حساب و پرداخت', 'Account and billing assistance'), value: '›' }, { icon: <AlertOctagon />, tone: 'danger', label: tx(locale, 'راهنمای ایمنی', 'Safety guidance'), detail: tx(locale, 'چه زمانی تمرین را متوقف کنی', 'When to stop exercising'), value: '›' }, { icon: <LockKeyhole />, label: tx(locale, 'حریم خصوصی', 'Privacy'), detail: tx(locale, 'نحوه استفاده و نگه‌داری داده‌ها', 'How data is used and retained'), value: '›' }, { icon: <ShieldCheck />, label: tx(locale, 'شرایط استفاده', 'Terms'), detail: tx(locale, 'محدوده و مسئولیت‌های سرویس', 'Service scope and responsibilities'), value: '›' }]} />
  return <SpecCard className="mo-spec__state-card"><span className="mo-spec__state-icon mo-spec__state-icon--warning">{icon}</span><h2>{tx(locale, 'از کجا خارج شوی؟', 'Where should we sign you out?')}</h2><p>{tx(locale, 'ثبت‌های همگام‌شده در حسابت باقی می‌مانند. موارد آفلاین را قبل از خروج همگام کن.', 'Synced entries stay in your account. Sync offline entries before signing out.')}</p><SpecList rows={[{ icon: <LogOut />, tone: 'brand', label: tx(locale, 'فقط این دستگاه', 'This device only'), detail: tx(locale, 'نشست‌های دیگر فعال می‌مانند', 'Other sessions remain active'), value: tx(locale, 'انتخاب شده', 'Selected') }, { icon: <ShieldCheck />, tone: 'warning', label: tx(locale, 'همه دستگاه‌ها', 'All devices'), detail: tx(locale, 'تمام نشست‌های فعال باطل می‌شوند', 'Every active session is revoked'), value: tx(locale, 'انتخاب', 'Choose') }]} /><SpecCallout icon={<CheckCircle2 />} title={tx(locale, 'همه اطلاعات همگام است', 'Everything is synced')} tone="success" /><SpecCallout icon={<AlertTriangle />} title={tx(locale, 'اگر خروج ناموفق شود', 'If sign-out fails')} tone="warning">{tx(locale, 'نشست فعلی فعال می‌ماند و می‌توانی بدون از دست‌دادن داده دوباره تلاش کنی. کد SIGNOUT-17 نمایش داده می‌شود.', 'The current session stays active and you can retry without losing data. Reference SIGNOUT-17 is shown.')}</SpecCallout><div className="mo-spec__actions"><SpecButton kind="secondary">{tx(locale, 'انصراف', 'Cancel')}</SpecButton><SpecButton kind="danger">{tx(locale, 'خروج از دستگاه انتخابی', 'Sign out selected devices')}</SpecButton></div></SpecCard>
}

function renderProgress(view: ProgressView) { return (_: unknown, context: { globals: Record<string, unknown> }) => { const locale = localeFromStory(context.globals.locale); const content = <ProgressScreen locale={locale} view={view} />; return ['normal', 'caution', 'referral'].includes(view) ? <SpecOverlay kind="sheet" locale={locale} title={tx(locale, 'نتیجه بررسی هفتگی', 'Weekly check-in result')}>{content}</SpecOverlay> : content } }
function renderProgressOffline() { return (_: unknown, context: { globals: Record<string, unknown> }) => <ProgressOfflineView locale={localeFromStory(context.globals.locale)} /> }
function renderWeeklyForm() { return (_: unknown, context: { globals: Record<string, unknown> }) => { const locale = localeFromStory(context.globals.locale); return <SpecOverlay kind="sheet" locale={locale} title={tx(locale, 'گزارش هفتگی', 'Weekly report')}><WeeklyCheckInForm locale={locale} /></SpecOverlay> } }
function renderNextCycle() { return (_: unknown, context: { globals: Record<string, unknown> }) => <NextCycleReadiness locale={localeFromStory(context.globals.locale)} /> }
function renderAccount(section: AccountSection) { return (_: unknown, context: { globals: Record<string, unknown> }) => { const locale = localeFromStory(context.globals.locale); const content = <AccountScreen locale={locale} section={section} />; return section === 'signout' ? <SpecOverlay kind="dialog" locale={locale} material="opaque" title={tx(locale, 'تأیید خروج', 'Confirm sign out')}>{content}</SpecOverlay> : content } }

const meta = { title: 'Screens/Complete product/Progress and account', parameters: { controls: { disable: true }, layout: 'fullscreen', docs: { description: { component: 'Monthly-plan progress, accessible chart alternatives, check-in outcomes, and every nested account hub. All data is local.' } } } } satisfies Meta
export default meta
type Story = StoryObj<typeof meta>

export const ProgressFourWeekOverview: Story = { parameters: momentumEvidence(['PROG-01'], '/[locale]/app/progress'), render: renderProgress('overview') }
export const ProgressTextAlternative: Story = { parameters: momentumEvidence(['PROG-02'], '/[locale]/app/progress'), render: renderProgress('text') }
export const ProgressTableAlternative: Story = { parameters: momentumEvidence(['PROG-02'], '/[locale]/app/progress'), render: renderProgress('table') }
export const ProgressEmpty: Story = { parameters: momentumEvidence(['PROG-03'], '/[locale]/app/progress'), render: renderProgress('empty') }
export const ProgressOffline: Story = { parameters: momentumEvidence(['PROG-04'], '/[locale]/app/progress'), render: renderProgressOffline() }
export const WeeklyCheckInDue: Story = { parameters: momentumEvidence(['PROG-05'], '/[locale]/app/progress', 'sheet'), render: renderWeeklyForm() }
export const WeeklyOutcomeNormal: Story = { parameters: momentumEvidence(['PROG-06'], '/[locale]/app/progress', 'sheet'), render: renderProgress('normal') }
export const WeeklyOutcomeCaution: Story = { parameters: momentumEvidence(['PROG-06'], '/[locale]/app/progress', 'sheet'), render: renderProgress('caution') }
export const WeeklyOutcomeProfessionalReferral: Story = { parameters: momentumEvidence(['PROG-06'], '/[locale]/app/progress', 'sheet'), render: renderProgress('referral') }
export const NextCycleReadinessScreen: Story = { parameters: momentumEvidence(['PROG-07'], '/[locale]/app/progress', 'in-page'), render: renderNextCycle() }
export const AccountOverview: Story = { parameters: momentumEvidence(['ME-01'], '/[locale]/app/me'), render: renderAccount('overview') }
export const ProfileAndGoals: Story = { parameters: momentumEvidence(['ME-02'], '/[locale]/app/settings'), render: renderAccount('profile') }
export const MeasurementsHistory: Story = { parameters: momentumEvidence(['ME-02'], '/[locale]/app/settings'), render: renderAccount('measurements') }
export const PlanPreferences: Story = { parameters: momentumEvidence(['ME-02'], '/[locale]/app/settings'), render: renderAccount('preferences') }
export const LanguageCalendarUnits: Story = { parameters: momentumEvidence(['ME-03'], '/[locale]/app/settings'), render: renderAccount('language') }
export const AccessibilityPreferences: Story = { parameters: momentumEvidence(['ME-03'], '/[locale]/app/settings'), render: renderAccount('accessibility') }
export const NotificationPreferences: Story = { parameters: momentumEvidence(['ME-04'], '/[locale]/app/settings'), render: renderAccount('notifications') }
export const SubscriptionDetails: Story = { parameters: momentumEvidence(['ME-05'], '/[locale]/app/me', 'in-page'), render: renderAccount('subscription') }
export const PlanHistory: Story = { parameters: momentumEvidence(['ME-05'], '/[locale]/app/me', 'in-page'), render: renderAccount('history') }
export const AccountDataExport: Story = { parameters: momentumEvidence(['ME-06'], '/[locale]/app/account'), render: renderAccount('data') }
export const DeleteAccountConfirmation: Story = { parameters: momentumEvidence(['ME-07'], '/[locale]/app/account'), render: renderAccount('delete') }
export const HelpSafetyAndLegal: Story = { parameters: momentumEvidence(['ME-08'], '/[locale]/app/me', 'in-page'), render: renderAccount('help') }
export const SignOutConfirmation: Story = { parameters: momentumEvidence(['ME-09'], '/[locale]/app/me', 'dialog'), render: renderAccount('signout') }
export const AccountOverviewMobile: Story = { parameters: { ...momentumEvidence(['ME-01'], '/[locale]/app/me'), viewport: { defaultViewport: 'mobile1' } }, render: renderAccount('overview') }
