begin;

-- Reviewed generation catalog. Retire the tiny v1 test seed but keep its rows.
-- Public generation loads the single active release (`momentum-core@v2`).
update public.catalog_releases
set status = 'retired'
where id = 'momentum-core@v1';

insert into public.catalog_releases(id, version, status, released_at)
values ('momentum-core@v2', 2, 'active', statement_timestamp());

insert into public.allergen_catalog(id, catalog_release_id, slug, name_en, name_fa, aliases)
values
  ('allergen:milk@v2', 'momentum-core@v2', 'milk', 'Milk', 'شیر', array['dairy', 'lactose', 'cow milk', 'لبنیات', 'شیر گاو']),
  ('allergen:egg@v2', 'momentum-core@v2', 'egg', 'Egg', 'تخم‌مرغ', array['eggs', 'تخم مرغ']),
  ('allergen:peanut@v2', 'momentum-core@v2', 'peanut', 'Peanut', 'بادام زمینی', array['groundnut', 'peanuts', 'بادام‌زمینی']),
  ('allergen:tree_nut@v2', 'momentum-core@v2', 'tree_nut', 'Tree nut', 'آجیل درختی', array['tree nut', 'nuts', 'walnut', 'almond', 'آجیل', 'گردو', 'بادام']),
  ('allergen:wheat@v2', 'momentum-core@v2', 'wheat', 'Wheat / gluten', 'گندم / گلوتن', array['gluten', 'wheat', 'گندم', 'گلوتن']),
  ('allergen:soy@v2', 'momentum-core@v2', 'soy', 'Soy', 'سویا', array['soya', 'soybean', 'سویا']),
  ('allergen:fish@v2', 'momentum-core@v2', 'fish', 'Fish', 'ماهی', array['tuna', 'salmon', 'ماهی']),
  ('allergen:shellfish@v2', 'momentum-core@v2', 'shellfish', 'Shellfish', 'صدف و سخت‌پوستان', array['shrimp', 'crustacean', 'صدف', 'میگو']),
  ('allergen:sesame@v2', 'momentum-core@v2', 'sesame', 'Sesame', 'کنجد', array['tahini', 'کنجد', 'ارده']);

insert into public.ingredient_catalog(id, catalog_release_id, slug, name_en, name_fa, default_unit)
values
  ('ingredient:chicken-breast@v2', 'momentum-core@v2', 'chicken-breast', 'Cooked chicken breast', 'سینه مرغ پخته', 'g'),
  ('ingredient:turkey-breast@v2', 'momentum-core@v2', 'turkey-breast', 'Cooked turkey breast', 'سینه بوقلمون پخته', 'g'),
  ('ingredient:lean-beef@v2', 'momentum-core@v2', 'lean-beef', 'Cooked lean beef', 'گوشت گوساله کم‌چرب پخته', 'g'),
  ('ingredient:canned-tuna@v2', 'momentum-core@v2', 'canned-tuna', 'Canned tuna in water', 'تن ماهی در آب', 'g'),
  ('ingredient:salmon@v2', 'momentum-core@v2', 'salmon', 'Cooked salmon', 'سالمون پخته', 'g'),
  ('ingredient:shrimp@v2', 'momentum-core@v2', 'shrimp', 'Cooked shrimp', 'میگو پخته', 'g'),
  ('ingredient:eggs@v2', 'momentum-core@v2', 'eggs', 'Eggs', 'تخم‌مرغ', 'piece'),
  ('ingredient:greek-yogurt@v2', 'momentum-core@v2', 'greek-yogurt', 'Greek yogurt', 'ماست یونانی', 'g'),
  ('ingredient:cottage-cheese@v2', 'momentum-core@v2', 'cottage-cheese', 'Cottage cheese', 'پنیر کاتیج', 'g'),
  ('ingredient:feta@v2', 'momentum-core@v2', 'feta', 'Feta cheese', 'پنیر فتا', 'g'),
  ('ingredient:tofu@v2', 'momentum-core@v2', 'tofu', 'Firm tofu', 'توفو سفت', 'g'),
  ('ingredient:red-lentils@v2', 'momentum-core@v2', 'red-lentils', 'Cooked red lentils', 'عدس قرمز پخته', 'g'),
  ('ingredient:chickpeas@v2', 'momentum-core@v2', 'chickpeas', 'Cooked chickpeas', 'نخود پخته', 'g'),
  ('ingredient:black-beans@v2', 'momentum-core@v2', 'black-beans', 'Cooked black beans', 'لوبیا سیاه پخته', 'g'),
  ('ingredient:brown-rice@v2', 'momentum-core@v2', 'brown-rice', 'Cooked brown rice', 'برنج قهوه‌ای پخته', 'g'),
  ('ingredient:white-rice@v2', 'momentum-core@v2', 'white-rice', 'Cooked white rice', 'برنج سفید پخته', 'g'),
  ('ingredient:oats@v2', 'momentum-core@v2', 'oats', 'Rolled oats', 'جو دوسر پرک', 'g'),
  ('ingredient:quinoa@v2', 'momentum-core@v2', 'quinoa', 'Cooked quinoa', 'کینوا پخته', 'g'),
  ('ingredient:whole-wheat-bread@v2', 'momentum-core@v2', 'whole-wheat-bread', 'Whole-wheat bread', 'نان سبوس‌دار', 'slice'),
  ('ingredient:pita-bread@v2', 'momentum-core@v2', 'pita-bread', 'Pita bread', 'نان پیتا', 'piece'),
  ('ingredient:pasta@v2', 'momentum-core@v2', 'pasta', 'Cooked wheat pasta', 'پاستای گندم پخته', 'g'),
  ('ingredient:potato@v2', 'momentum-core@v2', 'potato', 'Cooked potato', 'سیب‌زمینی پخته', 'g'),
  ('ingredient:sweet-potato@v2', 'momentum-core@v2', 'sweet-potato', 'Cooked sweet potato', 'سیب‌زمینی شیرین پخته', 'g'),
  ('ingredient:wheat-tortilla@v2', 'momentum-core@v2', 'wheat-tortilla', 'Wheat tortilla', 'نان تورتیلا گندم', 'piece'),
  ('ingredient:rice-cakes@v2', 'momentum-core@v2', 'rice-cakes', 'Rice cakes', 'رایس‌کیک', 'piece'),
  ('ingredient:banana@v2', 'momentum-core@v2', 'banana', 'Banana', 'موز', 'piece'),
  ('ingredient:apple@v2', 'momentum-core@v2', 'apple', 'Apple', 'سیب', 'piece'),
  ('ingredient:orange@v2', 'momentum-core@v2', 'orange', 'Orange', 'پرتقال', 'piece'),
  ('ingredient:dates@v2', 'momentum-core@v2', 'dates', 'Dates', 'خرما', 'piece'),
  ('ingredient:berries@v2', 'momentum-core@v2', 'berries', 'Mixed berries', 'توت مخلوط', 'g'),
  ('ingredient:spinach@v2', 'momentum-core@v2', 'spinach', 'Spinach', 'اسفناج', 'g'),
  ('ingredient:mixed-greens@v2', 'momentum-core@v2', 'mixed-greens', 'Mixed greens', 'سبزی سالاد', 'g'),
  ('ingredient:cucumber@v2', 'momentum-core@v2', 'cucumber', 'Cucumber', 'خیار', 'g'),
  ('ingredient:tomato@v2', 'momentum-core@v2', 'tomato', 'Tomato', 'گوجه‌فرنگی', 'g'),
  ('ingredient:carrot@v2', 'momentum-core@v2', 'carrot', 'Carrot', 'هویج', 'g'),
  ('ingredient:broccoli@v2', 'momentum-core@v2', 'broccoli', 'Broccoli', 'کلم بروکلی', 'g'),
  ('ingredient:onion@v2', 'momentum-core@v2', 'onion', 'Onion', 'پیاز', 'g'),
  ('ingredient:garlic@v2', 'momentum-core@v2', 'garlic', 'Garlic', 'سیر', 'g'),
  ('ingredient:lemon@v2', 'momentum-core@v2', 'lemon', 'Lemon', 'لیموترش', 'piece'),
  ('ingredient:avocado@v2', 'momentum-core@v2', 'avocado', 'Avocado', 'آووکادو', 'g'),
  ('ingredient:bell-pepper@v2', 'momentum-core@v2', 'bell-pepper', 'Bell pepper', 'فلفل دلمه‌ای', 'g'),
  ('ingredient:olive-oil@v2', 'momentum-core@v2', 'olive-oil', 'Olive oil', 'روغن زیتون', 'tsp'),
  ('ingredient:walnuts@v2', 'momentum-core@v2', 'walnuts', 'Walnuts', 'گردو', 'g'),
  ('ingredient:almonds@v2', 'momentum-core@v2', 'almonds', 'Almonds', 'بادام', 'g'),
  ('ingredient:peanut-butter@v2', 'momentum-core@v2', 'peanut-butter', 'Peanut butter', 'کره بادام‌زمینی', 'tbsp'),
  ('ingredient:tahini@v2', 'momentum-core@v2', 'tahini', 'Tahini', 'ارده', 'tbsp'),
  ('ingredient:sesame-seeds@v2', 'momentum-core@v2', 'sesame-seeds', 'Sesame seeds', 'کنجد', 'g'),
  ('ingredient:hummus@v2', 'momentum-core@v2', 'hummus', 'Hummus', 'حمص', 'g'),
  ('ingredient:soy-sauce@v2', 'momentum-core@v2', 'soy-sauce', 'Soy sauce', 'سس سویا', 'tbsp'),
  ('ingredient:honey@v2', 'momentum-core@v2', 'honey', 'Honey', 'عسل', 'tsp'),
  ('ingredient:milk@v2', 'momentum-core@v2', 'milk', 'Cow''s milk', 'شیر گاو', 'ml');

insert into public.ingredient_allergens(ingredient_id, allergen_id, relation)
values
  ('ingredient:canned-tuna@v2', 'allergen:fish@v2', 'contains'),
  ('ingredient:salmon@v2', 'allergen:fish@v2', 'contains'),
  ('ingredient:shrimp@v2', 'allergen:shellfish@v2', 'contains'),
  ('ingredient:eggs@v2', 'allergen:egg@v2', 'contains'),
  ('ingredient:greek-yogurt@v2', 'allergen:milk@v2', 'contains'),
  ('ingredient:cottage-cheese@v2', 'allergen:milk@v2', 'contains'),
  ('ingredient:feta@v2', 'allergen:milk@v2', 'contains'),
  ('ingredient:tofu@v2', 'allergen:soy@v2', 'contains'),
  ('ingredient:oats@v2', 'allergen:wheat@v2', 'may_contain'),
  ('ingredient:whole-wheat-bread@v2', 'allergen:wheat@v2', 'contains'),
  ('ingredient:pita-bread@v2', 'allergen:wheat@v2', 'contains'),
  ('ingredient:pasta@v2', 'allergen:wheat@v2', 'contains'),
  ('ingredient:wheat-tortilla@v2', 'allergen:wheat@v2', 'contains'),
  ('ingredient:walnuts@v2', 'allergen:tree_nut@v2', 'contains'),
  ('ingredient:almonds@v2', 'allergen:tree_nut@v2', 'contains'),
  ('ingredient:peanut-butter@v2', 'allergen:peanut@v2', 'contains'),
  ('ingredient:tahini@v2', 'allergen:sesame@v2', 'contains'),
  ('ingredient:sesame-seeds@v2', 'allergen:sesame@v2', 'contains'),
  ('ingredient:hummus@v2', 'allergen:sesame@v2', 'contains'),
  ('ingredient:soy-sauce@v2', 'allergen:soy@v2', 'contains'),
  ('ingredient:soy-sauce@v2', 'allergen:wheat@v2', 'contains'),
  ('ingredient:milk@v2', 'allergen:milk@v2', 'contains');

insert into public.food_catalog(
  id, catalog_release_id, slug, name_en, name_fa, meal_types,
  calories, protein_g, carbs_g, fat_g, fiber_g, portable
)
values
  ('food:oat-yogurt-bowl@v2', 'momentum-core@v2', 'oat-yogurt-bowl', 'Oat yogurt bowl', 'کاسه جو دوسر و ماست',
    array['breakfast'], 328, 12, 52, 8, 8, false),
  ('food:veggie-omelette@v2', 'momentum-core@v2', 'veggie-omelette', 'Veggie omelette', 'املت سبزیجات',
    array['breakfast'], 256, 20, 8, 16, 3, false),
  ('food:cucumber-feta-pita@v2', 'momentum-core@v2', 'cucumber-feta-pita', 'Cucumber feta pita', 'پیتا با خیار و فتا',
    array['breakfast', 'morning_snack'], 334, 16, 36, 14, 5, false),
  ('food:date-walnut-yogurt@v2', 'momentum-core@v2', 'date-walnut-yogurt', 'Date walnut yogurt', 'ماست با خرما و گردو',
    array['breakfast'], 344, 18, 32, 16, 5, false),
  ('food:shakshuka@v2', 'momentum-core@v2', 'shakshuka', 'Shakshuka', 'شکشوکا',
    array['breakfast'], 272, 18, 14, 16, 4, false),
  ('food:peanut-banana-toast@v2', 'momentum-core@v2', 'peanut-banana-toast', 'Peanut banana toast', 'تست موز و کره بادام‌زمینی',
    array['breakfast'], 368, 14, 42, 16, 6, false),
  ('food:overnight-oats@v2', 'momentum-core@v2', 'overnight-oats', 'Overnight oats', 'جو دوسر شب‌خواب',
    array['breakfast'], 328, 16, 48, 8, 8, true),
  ('food:tofu-scramble@v2', 'momentum-core@v2', 'tofu-scramble', 'Tofu scramble', 'توفوی همزده',
    array['breakfast'], 254, 22, 10, 14, 4, false),
  ('food:rice-egg-plate@v2', 'momentum-core@v2', 'rice-egg-plate', 'Rice and eggs', 'برنج و تخم‌مرغ',
    array['breakfast'], 340, 16, 42, 12, 2, false),
  ('food:cottage-berry-bowl@v2', 'momentum-core@v2', 'cottage-berry-bowl', 'Cottage berry bowl', 'کاسه پنیر کاتیج و توت',
    array['breakfast'], 238, 24, 22, 6, 4, false),
  ('food:herb-omelette@v2', 'momentum-core@v2', 'herb-omelette', 'Herb omelette', 'کوکوی سبزی',
    array['breakfast'], 274, 20, 8, 18, 3, false),
  ('food:noon-paneer-sabzi@v2', 'momentum-core@v2', 'noon-paneer-sabzi', 'Bread cheese and herbs', 'نان و پنیر و سبزی',
    array['breakfast'], 346, 14, 32, 18, 5, false),
  ('food:chicken-rice-bowl@v2', 'momentum-core@v2', 'chicken-rice-bowl', 'Chicken rice bowl', 'کاسه مرغ و برنج',
    array['lunch', 'dinner'], 544, 45, 55, 16, 6, false),
  ('food:lentil-stew-rice@v2', 'momentum-core@v2', 'lentil-stew-rice', 'Lentil stew with rice', 'خورش عدس با برنج',
    array['lunch', 'dinner'], 468, 22, 68, 12, 16, false),
  ('food:salmon-quinoa-salad@v2', 'momentum-core@v2', 'salmon-quinoa-salad', 'Salmon quinoa salad', 'سالاد سالمون و کینوا',
    array['lunch'], 492, 38, 40, 20, 7, false),
  ('food:chickpea-salad@v2', 'momentum-core@v2', 'chickpea-salad', 'Chickpea salad', 'سالاد نخود',
    array['lunch'], 358, 16, 42, 14, 12, false),
  ('food:tuna-pita@v2', 'momentum-core@v2', 'tuna-pita', 'Tuna pita', 'پیتای تن ماهی',
    array['lunch'], 354, 32, 34, 10, 5, true),
  ('food:turkey-rice-bowl@v2', 'momentum-core@v2', 'turkey-rice-bowl', 'Turkey rice bowl', 'کاسه بوقلمون و برنج',
    array['lunch', 'dinner'], 484, 42, 52, 12, 6, false),
  ('food:tofu-stir-fry-rice@v2', 'momentum-core@v2', 'tofu-stir-fry-rice', 'Tofu stir-fry rice', 'توفو تفت‌داده‌شده با برنج',
    array['lunch', 'dinner'], 454, 24, 58, 14, 7, false),
  ('food:beef-potato-stew@v2', 'momentum-core@v2', 'beef-potato-stew', 'Beef potato stew', 'خورش گوشت و سیب‌زمینی',
    array['lunch', 'dinner'], 448, 36, 40, 16, 6, false),
  ('food:falafel-hummus-plate@v2', 'momentum-core@v2', 'falafel-hummus-plate', 'Falafel hummus plate', 'بشقاب فلافل و حمص',
    array['lunch'], 442, 18, 52, 18, 12, false),
  ('food:shrimp-rice-bowl@v2', 'momentum-core@v2', 'shrimp-rice-bowl', 'Shrimp rice bowl', 'کاسه میگو و برنج',
    array['lunch', 'dinner'], 418, 32, 50, 10, 5, false),
  ('food:black-bean-bowl@v2', 'momentum-core@v2', 'black-bean-bowl', 'Black bean bowl', 'کاسه لوبیا سیاه',
    array['lunch'], 430, 18, 58, 14, 14, false),
  ('food:grilled-chicken-salad@v2', 'momentum-core@v2', 'grilled-chicken-salad', 'Grilled chicken salad', 'سالاد مرغ گریل',
    array['lunch'], 352, 40, 12, 16, 5, false),
  ('food:chicken-sweet-potato@v2', 'momentum-core@v2', 'chicken-sweet-potato', 'Chicken and sweet potato', 'مرغ و سیب‌زمینی شیرین',
    array['dinner'], 486, 42, 48, 14, 8, false),
  ('food:baked-salmon-potato@v2', 'momentum-core@v2', 'baked-salmon-potato', 'Baked salmon potato', 'سالمون و سیب‌زمینی',
    array['dinner'], 450, 36, 36, 18, 5, false),
  ('food:turkey-quinoa-bowl@v2', 'momentum-core@v2', 'turkey-quinoa-bowl', 'Turkey quinoa bowl', 'کاسه بوقلمون و کینوا',
    array['dinner'], 444, 40, 44, 12, 7, false),
  ('food:lentil-pasta@v2', 'momentum-core@v2', 'lentil-pasta', 'Lentil pasta', 'پاستا با عدس',
    array['dinner'], 492, 24, 72, 12, 14, false),
  ('food:beef-rice-veg@v2', 'momentum-core@v2', 'beef-rice-veg', 'Beef rice vegetables', 'گوشت و برنج و سبزی',
    array['dinner'], 480, 34, 50, 16, 6, false),
  ('food:tofu-sesame-bowl@v2', 'momentum-core@v2', 'tofu-sesame-bowl', 'Sesame tofu bowl', 'کاسه توفو کنجدی',
    array['dinner'], 440, 22, 52, 16, 6, false),
  ('food:shrimp-quinoa-bowl@v2', 'momentum-core@v2', 'shrimp-quinoa-bowl', 'Shrimp quinoa bowl', 'کاسه میگو و کینوا',
    array['dinner'], 378, 30, 42, 10, 6, false),
  ('food:chickpea-tomato-rice@v2', 'momentum-core@v2', 'chickpea-tomato-rice', 'Chickpea tomato rice', 'نخود و گوجه با برنج',
    array['dinner'], 410, 16, 64, 10, 12, false),
  ('food:egg-salad-plate@v2', 'momentum-core@v2', 'egg-salad-plate', 'Egg salad plate', 'بشقاب تخم‌مرغ و سالاد',
    array['dinner'], 274, 18, 10, 18, 4, false),
  ('food:yogurt-chicken-rice@v2', 'momentum-core@v2', 'yogurt-chicken-rice', 'Yogurt chicken rice', 'مرغ و ماست و برنج',
    array['dinner'], 502, 44, 50, 14, 3, false),
  ('food:potato-spinach-eggs@v2', 'momentum-core@v2', 'potato-spinach-eggs', 'Potato spinach eggs', 'سیب‌زمینی و اسفناج و تخم‌مرغ',
    array['dinner'], 342, 18, 36, 14, 5, false),
  ('food:bean-veggie-chili@v2', 'momentum-core@v2', 'bean-veggie-chili', 'Bean vegetable chili', 'چیلی لوبیا و سبزی',
    array['dinner'], 368, 18, 56, 8, 16, false),
  ('food:banana-almonds@v2', 'momentum-core@v2', 'banana-almonds', 'Banana and almonds', 'موز و بادام',
    array['morning_snack', 'afternoon_snack'], 270, 8, 28, 14, 6, true),
  ('food:apple-peanut-butter@v2', 'momentum-core@v2', 'apple-peanut-butter', 'Apple with peanut butter', 'سیب و کره بادام‌زمینی',
    array['morning_snack', 'afternoon_snack'], 288, 8, 28, 16, 6, true),
  ('food:yogurt-honey-cup@v2', 'momentum-core@v2', 'yogurt-honey-cup', 'Yogurt honey cup', 'ماست و عسل',
    array['morning_snack', 'afternoon_snack'], 172, 16, 18, 4, 0, true),
  ('food:carrot-hummus@v2', 'momentum-core@v2', 'carrot-hummus', 'Carrot and hummus', 'هویج و حمص',
    array['morning_snack', 'afternoon_snack'], 176, 6, 20, 8, 7, true),
  ('food:dates-walnuts@v2', 'momentum-core@v2', 'dates-walnuts', 'Dates and walnuts', 'خرما و گردو',
    array['morning_snack', 'afternoon_snack', 'pre_sleep'], 278, 6, 32, 14, 5, true),
  ('food:rice-cake-peanut@v2', 'momentum-core@v2', 'rice-cake-peanut', 'Rice cakes with peanut butter', 'رایس‌کیک و کره بادام‌زمینی',
    array['morning_snack', 'afternoon_snack'], 254, 8, 24, 14, 3, true),
  ('food:boiled-eggs@v2', 'momentum-core@v2', 'boiled-eggs', 'Boiled eggs', 'تخم‌مرغ آب‌پز',
    array['breakfast', 'morning_snack', 'afternoon_snack'], 142, 12, 1, 10, 0, true),
  ('food:cucumber-feta@v2', 'momentum-core@v2', 'cucumber-feta', 'Cucumber and feta', 'خیار و پنیر فتا',
    array['afternoon_snack'], 146, 8, 6, 10, 1, false),
  ('food:berry-yogurt@v2', 'momentum-core@v2', 'berry-yogurt', 'Berry yogurt', 'ماست و توت',
    array['morning_snack', 'afternoon_snack'], 180, 14, 22, 4, 4, true),
  ('food:oat-date-tahini@v2', 'momentum-core@v2', 'oat-date-tahini', 'Oat date tahini bites', 'توپک جو دوسر و ارده',
    array['afternoon_snack'], 284, 8, 36, 12, 6, true),
  ('food:orange-almonds@v2', 'momentum-core@v2', 'orange-almonds', 'Orange and almonds', 'پرتقال و بادام',
    array['morning_snack', 'afternoon_snack'], 220, 6, 22, 12, 5, true),
  ('food:turkey-veggie-wrap@v2', 'momentum-core@v2', 'turkey-veggie-wrap', 'Turkey veggie wrap', 'رول بوقلمون و سبزی',
    array['lunch', 'afternoon_snack'], 312, 28, 32, 8, 5, true),
  ('food:mast-o-khiar@v2', 'momentum-core@v2', 'mast-o-khiar', 'Yogurt cucumber', 'ماست و خیار',
    array['afternoon_snack', 'dinner'], 124, 12, 10, 4, 1, false),
  ('food:fresh-banana@v2', 'momentum-core@v2', 'fresh-banana', 'Fresh banana', 'موز تازه',
    array['breakfast', 'morning_snack', 'afternoon_snack'], 116, 2, 27, 0, 3, true),
  ('food:fresh-apple@v2', 'momentum-core@v2', 'fresh-apple', 'Fresh apple', 'سیب تازه',
    array['morning_snack', 'afternoon_snack'], 104, 1, 25, 0, 4, true),
  ('food:cottage-cucumber@v2', 'momentum-core@v2', 'cottage-cucumber', 'Cottage cucumber', 'پنیر کاتیج و خیار',
    array['pre_sleep'], 148, 20, 8, 4, 1, false),
  ('food:yogurt-banana-night@v2', 'momentum-core@v2', 'yogurt-banana-night', 'Night yogurt banana', 'ماست و موز شب',
    array['pre_sleep'], 228, 16, 32, 4, 3, false),
  ('food:warm-milk-dates@v2', 'momentum-core@v2', 'warm-milk-dates', 'Warm milk and dates', 'شیر گرم و خرما',
    array['pre_sleep'], 206, 10, 28, 6, 3, false),
  ('food:turkey-cucumber-plate@v2', 'momentum-core@v2', 'turkey-cucumber-plate', 'Turkey cucumber plate', 'بوقلمون و خیار',
    array['pre_sleep', 'afternoon_snack'], 122, 22, 4, 2, 1, true),
  ('food:chickpea-lemon-cup@v2', 'momentum-core@v2', 'chickpea-lemon-cup', 'Chickpea lemon cup', 'نخود و لیمو',
    array['afternoon_snack', 'pre_sleep'], 172, 10, 24, 4, 7, true);

insert into public.food_catalog_ingredients(food_id, ingredient_id, amount, unit, position)
values
  ('food:oat-yogurt-bowl@v2', 'ingredient:oats@v2', 50, 'g', 1),
  ('food:oat-yogurt-bowl@v2', 'ingredient:greek-yogurt@v2', 120, 'g', 2),
  ('food:oat-yogurt-bowl@v2', 'ingredient:banana@v2', 1, 'piece', 3),
  ('food:oat-yogurt-bowl@v2', 'ingredient:honey@v2', 1, 'tsp', 4),
  ('food:veggie-omelette@v2', 'ingredient:eggs@v2', 2, 'piece', 1),
  ('food:veggie-omelette@v2', 'ingredient:spinach@v2', 60, 'g', 2),
  ('food:veggie-omelette@v2', 'ingredient:tomato@v2', 80, 'g', 3),
  ('food:veggie-omelette@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 4),
  ('food:cucumber-feta-pita@v2', 'ingredient:pita-bread@v2', 1, 'piece', 1),
  ('food:cucumber-feta-pita@v2', 'ingredient:feta@v2', 40, 'g', 2),
  ('food:cucumber-feta-pita@v2', 'ingredient:cucumber@v2', 100, 'g', 3),
  ('food:cucumber-feta-pita@v2', 'ingredient:tomato@v2', 80, 'g', 4),
  ('food:cucumber-feta-pita@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 5),
  ('food:date-walnut-yogurt@v2', 'ingredient:greek-yogurt@v2', 200, 'g', 1),
  ('food:date-walnut-yogurt@v2', 'ingredient:dates@v2', 3, 'piece', 2),
  ('food:date-walnut-yogurt@v2', 'ingredient:walnuts@v2', 20, 'g', 3),
  ('food:shakshuka@v2', 'ingredient:eggs@v2', 2, 'piece', 1),
  ('food:shakshuka@v2', 'ingredient:tomato@v2', 200, 'g', 2),
  ('food:shakshuka@v2', 'ingredient:onion@v2', 50, 'g', 3),
  ('food:shakshuka@v2', 'ingredient:olive-oil@v2', 2, 'tsp', 4),
  ('food:peanut-banana-toast@v2', 'ingredient:whole-wheat-bread@v2', 2, 'slice', 1),
  ('food:peanut-banana-toast@v2', 'ingredient:peanut-butter@v2', 2, 'tbsp', 2),
  ('food:peanut-banana-toast@v2', 'ingredient:banana@v2', 1, 'piece', 3),
  ('food:overnight-oats@v2', 'ingredient:oats@v2', 50, 'g', 1),
  ('food:overnight-oats@v2', 'ingredient:milk@v2', 200, 'ml', 2),
  ('food:overnight-oats@v2', 'ingredient:berries@v2', 80, 'g', 3),
  ('food:overnight-oats@v2', 'ingredient:honey@v2', 1, 'tsp', 4),
  ('food:tofu-scramble@v2', 'ingredient:tofu@v2', 150, 'g', 1),
  ('food:tofu-scramble@v2', 'ingredient:spinach@v2', 60, 'g', 2),
  ('food:tofu-scramble@v2', 'ingredient:onion@v2', 40, 'g', 3),
  ('food:tofu-scramble@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 4),
  ('food:rice-egg-plate@v2', 'ingredient:white-rice@v2', 180, 'g', 1),
  ('food:rice-egg-plate@v2', 'ingredient:eggs@v2', 2, 'piece', 2),
  ('food:rice-egg-plate@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 3),
  ('food:cottage-berry-bowl@v2', 'ingredient:cottage-cheese@v2', 200, 'g', 1),
  ('food:cottage-berry-bowl@v2', 'ingredient:berries@v2', 100, 'g', 2),
  ('food:cottage-berry-bowl@v2', 'ingredient:honey@v2', 1, 'tsp', 3),
  ('food:herb-omelette@v2', 'ingredient:eggs@v2', 2, 'piece', 1),
  ('food:herb-omelette@v2', 'ingredient:spinach@v2', 80, 'g', 2),
  ('food:herb-omelette@v2', 'ingredient:onion@v2', 30, 'g', 3),
  ('food:herb-omelette@v2', 'ingredient:olive-oil@v2', 2, 'tsp', 4),
  ('food:noon-paneer-sabzi@v2', 'ingredient:pita-bread@v2', 1, 'piece', 1),
  ('food:noon-paneer-sabzi@v2', 'ingredient:feta@v2', 40, 'g', 2),
  ('food:noon-paneer-sabzi@v2', 'ingredient:spinach@v2', 40, 'g', 3),
  ('food:noon-paneer-sabzi@v2', 'ingredient:walnuts@v2', 15, 'g', 4),
  ('food:noon-paneer-sabzi@v2', 'ingredient:cucumber@v2', 80, 'g', 5),
  ('food:chicken-rice-bowl@v2', 'ingredient:chicken-breast@v2', 180, 'g', 1),
  ('food:chicken-rice-bowl@v2', 'ingredient:brown-rice@v2', 200, 'g', 2),
  ('food:chicken-rice-bowl@v2', 'ingredient:spinach@v2', 80, 'g', 3),
  ('food:chicken-rice-bowl@v2', 'ingredient:olive-oil@v2', 2, 'tsp', 4),
  ('food:lentil-stew-rice@v2', 'ingredient:red-lentils@v2', 250, 'g', 1),
  ('food:lentil-stew-rice@v2', 'ingredient:brown-rice@v2', 150, 'g', 2),
  ('food:lentil-stew-rice@v2', 'ingredient:onion@v2', 60, 'g', 3),
  ('food:lentil-stew-rice@v2', 'ingredient:spinach@v2', 60, 'g', 4),
  ('food:lentil-stew-rice@v2', 'ingredient:olive-oil@v2', 2, 'tsp', 5),
  ('food:salmon-quinoa-salad@v2', 'ingredient:salmon@v2', 150, 'g', 1),
  ('food:salmon-quinoa-salad@v2', 'ingredient:quinoa@v2', 180, 'g', 2),
  ('food:salmon-quinoa-salad@v2', 'ingredient:mixed-greens@v2', 80, 'g', 3),
  ('food:salmon-quinoa-salad@v2', 'ingredient:lemon@v2', 1, 'piece', 4),
  ('food:salmon-quinoa-salad@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 5),
  ('food:chickpea-salad@v2', 'ingredient:chickpeas@v2', 200, 'g', 1),
  ('food:chickpea-salad@v2', 'ingredient:cucumber@v2', 100, 'g', 2),
  ('food:chickpea-salad@v2', 'ingredient:tomato@v2', 100, 'g', 3),
  ('food:chickpea-salad@v2', 'ingredient:olive-oil@v2', 2, 'tsp', 4),
  ('food:chickpea-salad@v2', 'ingredient:lemon@v2', 1, 'piece', 5),
  ('food:tuna-pita@v2', 'ingredient:canned-tuna@v2', 120, 'g', 1),
  ('food:tuna-pita@v2', 'ingredient:pita-bread@v2', 1, 'piece', 2),
  ('food:tuna-pita@v2', 'ingredient:cucumber@v2', 80, 'g', 3),
  ('food:tuna-pita@v2', 'ingredient:mixed-greens@v2', 40, 'g', 4),
  ('food:turkey-rice-bowl@v2', 'ingredient:turkey-breast@v2', 180, 'g', 1),
  ('food:turkey-rice-bowl@v2', 'ingredient:brown-rice@v2', 200, 'g', 2),
  ('food:turkey-rice-bowl@v2', 'ingredient:broccoli@v2', 100, 'g', 3),
  ('food:turkey-rice-bowl@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 4),
  ('food:tofu-stir-fry-rice@v2', 'ingredient:tofu@v2', 150, 'g', 1),
  ('food:tofu-stir-fry-rice@v2', 'ingredient:brown-rice@v2', 200, 'g', 2),
  ('food:tofu-stir-fry-rice@v2', 'ingredient:broccoli@v2', 100, 'g', 3),
  ('food:tofu-stir-fry-rice@v2', 'ingredient:bell-pepper@v2', 80, 'g', 4),
  ('food:tofu-stir-fry-rice@v2', 'ingredient:soy-sauce@v2', 1, 'tbsp', 5),
  ('food:beef-potato-stew@v2', 'ingredient:lean-beef@v2', 150, 'g', 1),
  ('food:beef-potato-stew@v2', 'ingredient:potato@v2', 200, 'g', 2),
  ('food:beef-potato-stew@v2', 'ingredient:carrot@v2', 80, 'g', 3),
  ('food:beef-potato-stew@v2', 'ingredient:onion@v2', 50, 'g', 4),
  ('food:beef-potato-stew@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 5),
  ('food:falafel-hummus-plate@v2', 'ingredient:chickpeas@v2', 150, 'g', 1),
  ('food:falafel-hummus-plate@v2', 'ingredient:hummus@v2', 80, 'g', 2),
  ('food:falafel-hummus-plate@v2', 'ingredient:pita-bread@v2', 1, 'piece', 3),
  ('food:falafel-hummus-plate@v2', 'ingredient:cucumber@v2', 80, 'g', 4),
  ('food:falafel-hummus-plate@v2', 'ingredient:tahini@v2', 1, 'tbsp', 5),
  ('food:shrimp-rice-bowl@v2', 'ingredient:shrimp@v2', 150, 'g', 1),
  ('food:shrimp-rice-bowl@v2', 'ingredient:white-rice@v2', 200, 'g', 2),
  ('food:shrimp-rice-bowl@v2', 'ingredient:broccoli@v2', 80, 'g', 3),
  ('food:shrimp-rice-bowl@v2', 'ingredient:garlic@v2', 10, 'g', 4),
  ('food:shrimp-rice-bowl@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 5),
  ('food:black-bean-bowl@v2', 'ingredient:black-beans@v2', 200, 'g', 1),
  ('food:black-bean-bowl@v2', 'ingredient:brown-rice@v2', 150, 'g', 2),
  ('food:black-bean-bowl@v2', 'ingredient:avocado@v2', 50, 'g', 3),
  ('food:black-bean-bowl@v2', 'ingredient:tomato@v2', 80, 'g', 4),
  ('food:black-bean-bowl@v2', 'ingredient:lemon@v2', 1, 'piece', 5),
  ('food:grilled-chicken-salad@v2', 'ingredient:chicken-breast@v2', 180, 'g', 1),
  ('food:grilled-chicken-salad@v2', 'ingredient:mixed-greens@v2', 100, 'g', 2),
  ('food:grilled-chicken-salad@v2', 'ingredient:cucumber@v2', 80, 'g', 3),
  ('food:grilled-chicken-salad@v2', 'ingredient:tomato@v2', 80, 'g', 4),
  ('food:grilled-chicken-salad@v2', 'ingredient:olive-oil@v2', 2, 'tsp', 5),
  ('food:chicken-sweet-potato@v2', 'ingredient:chicken-breast@v2', 180, 'g', 1),
  ('food:chicken-sweet-potato@v2', 'ingredient:sweet-potato@v2', 220, 'g', 2),
  ('food:chicken-sweet-potato@v2', 'ingredient:broccoli@v2', 100, 'g', 3),
  ('food:chicken-sweet-potato@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 4),
  ('food:baked-salmon-potato@v2', 'ingredient:salmon@v2', 150, 'g', 1),
  ('food:baked-salmon-potato@v2', 'ingredient:potato@v2', 200, 'g', 2),
  ('food:baked-salmon-potato@v2', 'ingredient:spinach@v2', 80, 'g', 3),
  ('food:baked-salmon-potato@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 4),
  ('food:turkey-quinoa-bowl@v2', 'ingredient:turkey-breast@v2', 170, 'g', 1),
  ('food:turkey-quinoa-bowl@v2', 'ingredient:quinoa@v2', 180, 'g', 2),
  ('food:turkey-quinoa-bowl@v2', 'ingredient:mixed-greens@v2', 80, 'g', 3),
  ('food:turkey-quinoa-bowl@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 4),
  ('food:lentil-pasta@v2', 'ingredient:pasta@v2', 200, 'g', 1),
  ('food:lentil-pasta@v2', 'ingredient:red-lentils@v2', 180, 'g', 2),
  ('food:lentil-pasta@v2', 'ingredient:tomato@v2', 120, 'g', 3),
  ('food:lentil-pasta@v2', 'ingredient:spinach@v2', 60, 'g', 4),
  ('food:lentil-pasta@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 5),
  ('food:beef-rice-veg@v2', 'ingredient:lean-beef@v2', 150, 'g', 1),
  ('food:beef-rice-veg@v2', 'ingredient:brown-rice@v2', 180, 'g', 2),
  ('food:beef-rice-veg@v2', 'ingredient:carrot@v2', 80, 'g', 3),
  ('food:beef-rice-veg@v2', 'ingredient:broccoli@v2', 80, 'g', 4),
  ('food:beef-rice-veg@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 5),
  ('food:tofu-sesame-bowl@v2', 'ingredient:tofu@v2', 150, 'g', 1),
  ('food:tofu-sesame-bowl@v2', 'ingredient:brown-rice@v2', 180, 'g', 2),
  ('food:tofu-sesame-bowl@v2', 'ingredient:broccoli@v2', 80, 'g', 3),
  ('food:tofu-sesame-bowl@v2', 'ingredient:sesame-seeds@v2', 10, 'g', 4),
  ('food:tofu-sesame-bowl@v2', 'ingredient:soy-sauce@v2', 1, 'tbsp', 5),
  ('food:shrimp-quinoa-bowl@v2', 'ingredient:shrimp@v2', 140, 'g', 1),
  ('food:shrimp-quinoa-bowl@v2', 'ingredient:quinoa@v2', 180, 'g', 2),
  ('food:shrimp-quinoa-bowl@v2', 'ingredient:bell-pepper@v2', 80, 'g', 3),
  ('food:shrimp-quinoa-bowl@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 4),
  ('food:chickpea-tomato-rice@v2', 'ingredient:chickpeas@v2', 200, 'g', 1),
  ('food:chickpea-tomato-rice@v2', 'ingredient:white-rice@v2', 180, 'g', 2),
  ('food:chickpea-tomato-rice@v2', 'ingredient:tomato@v2', 120, 'g', 3),
  ('food:chickpea-tomato-rice@v2', 'ingredient:onion@v2', 50, 'g', 4),
  ('food:chickpea-tomato-rice@v2', 'ingredient:spinach@v2', 60, 'g', 5),
  ('food:chickpea-tomato-rice@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 6),
  ('food:egg-salad-plate@v2', 'ingredient:eggs@v2', 2, 'piece', 1),
  ('food:egg-salad-plate@v2', 'ingredient:mixed-greens@v2', 100, 'g', 2),
  ('food:egg-salad-plate@v2', 'ingredient:tomato@v2', 80, 'g', 3),
  ('food:egg-salad-plate@v2', 'ingredient:cucumber@v2', 80, 'g', 4),
  ('food:egg-salad-plate@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 5),
  ('food:yogurt-chicken-rice@v2', 'ingredient:chicken-breast@v2', 170, 'g', 1),
  ('food:yogurt-chicken-rice@v2', 'ingredient:greek-yogurt@v2', 100, 'g', 2),
  ('food:yogurt-chicken-rice@v2', 'ingredient:cucumber@v2', 80, 'g', 3),
  ('food:yogurt-chicken-rice@v2', 'ingredient:white-rice@v2', 180, 'g', 4),
  ('food:potato-spinach-eggs@v2', 'ingredient:potato@v2', 220, 'g', 1),
  ('food:potato-spinach-eggs@v2', 'ingredient:eggs@v2', 2, 'piece', 2),
  ('food:potato-spinach-eggs@v2', 'ingredient:spinach@v2', 80, 'g', 3),
  ('food:potato-spinach-eggs@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 4),
  ('food:bean-veggie-chili@v2', 'ingredient:black-beans@v2', 220, 'g', 1),
  ('food:bean-veggie-chili@v2', 'ingredient:tomato@v2', 150, 'g', 2),
  ('food:bean-veggie-chili@v2', 'ingredient:onion@v2', 50, 'g', 3),
  ('food:bean-veggie-chili@v2', 'ingredient:bell-pepper@v2', 80, 'g', 4),
  ('food:bean-veggie-chili@v2', 'ingredient:brown-rice@v2', 120, 'g', 5),
  ('food:banana-almonds@v2', 'ingredient:banana@v2', 1, 'piece', 1),
  ('food:banana-almonds@v2', 'ingredient:almonds@v2', 20, 'g', 2),
  ('food:apple-peanut-butter@v2', 'ingredient:apple@v2', 1, 'piece', 1),
  ('food:apple-peanut-butter@v2', 'ingredient:peanut-butter@v2', 2, 'tbsp', 2),
  ('food:yogurt-honey-cup@v2', 'ingredient:greek-yogurt@v2', 170, 'g', 1),
  ('food:yogurt-honey-cup@v2', 'ingredient:honey@v2', 1, 'tsp', 2),
  ('food:carrot-hummus@v2', 'ingredient:carrot@v2', 120, 'g', 1),
  ('food:carrot-hummus@v2', 'ingredient:hummus@v2', 80, 'g', 2),
  ('food:dates-walnuts@v2', 'ingredient:dates@v2', 4, 'piece', 1),
  ('food:dates-walnuts@v2', 'ingredient:walnuts@v2', 20, 'g', 2),
  ('food:rice-cake-peanut@v2', 'ingredient:rice-cakes@v2', 2, 'piece', 1),
  ('food:rice-cake-peanut@v2', 'ingredient:peanut-butter@v2', 2, 'tbsp', 2),
  ('food:boiled-eggs@v2', 'ingredient:eggs@v2', 2, 'piece', 1),
  ('food:cucumber-feta@v2', 'ingredient:cucumber@v2', 150, 'g', 1),
  ('food:cucumber-feta@v2', 'ingredient:feta@v2', 40, 'g', 2),
  ('food:berry-yogurt@v2', 'ingredient:greek-yogurt@v2', 150, 'g', 1),
  ('food:berry-yogurt@v2', 'ingredient:berries@v2', 80, 'g', 2),
  ('food:oat-date-tahini@v2', 'ingredient:oats@v2', 30, 'g', 1),
  ('food:oat-date-tahini@v2', 'ingredient:dates@v2', 3, 'piece', 2),
  ('food:oat-date-tahini@v2', 'ingredient:tahini@v2', 1, 'tbsp', 3),
  ('food:orange-almonds@v2', 'ingredient:orange@v2', 1, 'piece', 1),
  ('food:orange-almonds@v2', 'ingredient:almonds@v2', 18, 'g', 2),
  ('food:turkey-veggie-wrap@v2', 'ingredient:wheat-tortilla@v2', 1, 'piece', 1),
  ('food:turkey-veggie-wrap@v2', 'ingredient:turkey-breast@v2', 100, 'g', 2),
  ('food:turkey-veggie-wrap@v2', 'ingredient:cucumber@v2', 60, 'g', 3),
  ('food:turkey-veggie-wrap@v2', 'ingredient:mixed-greens@v2', 40, 'g', 4),
  ('food:mast-o-khiar@v2', 'ingredient:greek-yogurt@v2', 180, 'g', 1),
  ('food:mast-o-khiar@v2', 'ingredient:cucumber@v2', 120, 'g', 2),
  ('food:fresh-banana@v2', 'ingredient:banana@v2', 1, 'piece', 1),
  ('food:fresh-apple@v2', 'ingredient:apple@v2', 1, 'piece', 1),
  ('food:cottage-cucumber@v2', 'ingredient:cottage-cheese@v2', 180, 'g', 1),
  ('food:cottage-cucumber@v2', 'ingredient:cucumber@v2', 100, 'g', 2),
  ('food:yogurt-banana-night@v2', 'ingredient:greek-yogurt@v2', 150, 'g', 1),
  ('food:yogurt-banana-night@v2', 'ingredient:banana@v2', 1, 'piece', 2),
  ('food:warm-milk-dates@v2', 'ingredient:milk@v2', 250, 'ml', 1),
  ('food:warm-milk-dates@v2', 'ingredient:dates@v2', 3, 'piece', 2),
  ('food:turkey-cucumber-plate@v2', 'ingredient:turkey-breast@v2', 100, 'g', 1),
  ('food:turkey-cucumber-plate@v2', 'ingredient:cucumber@v2', 120, 'g', 2),
  ('food:chickpea-lemon-cup@v2', 'ingredient:chickpeas@v2', 120, 'g', 1),
  ('food:chickpea-lemon-cup@v2', 'ingredient:lemon@v2', 1, 'piece', 2),
  ('food:chickpea-lemon-cup@v2', 'ingredient:olive-oil@v2', 1, 'tsp', 3);

insert into public.equipment_catalog(id, catalog_release_id, slug, name_en, name_fa)
values
  ('equipment:bodyweight@v2', 'momentum-core@v2', 'bodyweight', 'Bodyweight', 'وزن بدن'),
  ('equipment:wall@v2', 'momentum-core@v2', 'wall', 'Wall', 'دیوار'),
  ('equipment:yoga-mat@v2', 'momentum-core@v2', 'yoga-mat', 'Yoga mat', 'مت یوگا'),
  ('equipment:chair@v2', 'momentum-core@v2', 'chair', 'Chair', 'صندلی'),
  ('equipment:dumbbells@v2', 'momentum-core@v2', 'dumbbells', 'Dumbbells', 'دمبل'),
  ('equipment:resistance-band@v2', 'momentum-core@v2', 'resistance-band', 'Resistance band', 'کش مقاومتی'),
  ('equipment:kettlebell@v2', 'momentum-core@v2', 'kettlebell', 'Kettlebell', 'کتل‌بل'),
  ('equipment:jump-rope@v2', 'momentum-core@v2', 'jump-rope', 'Jump rope', 'طناب ورزشی');

insert into public.exercise_catalog(
  id, catalog_release_id, slug, name_en, name_fa, movement_pattern,
  instructions_en, instructions_fa, contraindication_tags
)
values
  ('exercise:sit-to-stand@v2', 'momentum-core@v2', 'sit-to-stand', 'Sit to stand', 'بلند شدن از صندلی', 'squat',
    'Sit tall, then stand by pressing through the whole foot without using momentum.',
    'صاف بنشینید و بدون تاب دادن بدن، با فشار پا بایستید.',
    array['knee']),
  ('exercise:bodyweight-squat@v2', 'momentum-core@v2', 'bodyweight-squat', 'Bodyweight squat', 'اسکوات با وزن بدن', 'squat',
    'Sit back with control and stand while keeping the knees aligned with the feet.',
    'با کنترل به عقب بنشینید و با هم‌راستا نگه‌داشتن زانو و پا بایستید.',
    array['knee']),
  ('exercise:goblet-squat@v2', 'momentum-core@v2', 'goblet-squat', 'Goblet squat', 'اسکوات گابلت', 'squat',
    'Hold a dumbbell at the chest, sit between the heels, and stand without collapsing the torso.',
    'دمبل را جلوی سینه بگیرید، بین پاشنه‌ها بنشینید و بدون جمع شدن تنه بایستید.',
    array['knee']),
  ('exercise:split-squat@v2', 'momentum-core@v2', 'split-squat', 'Split squat', 'اسکوات جدا', 'squat',
    'Step one foot back, lower the rear knee with control, then press the front foot to stand.',
    'یک پا را عقب بگذارید، زانوی عقب را کنترل‌شده پایین ببرید و با پای جلو بایستید.',
    array['knee', 'hip']),
  ('exercise:glute-bridge@v2', 'momentum-core@v2', 'glute-bridge', 'Glute bridge', 'پل باسن', 'hinge',
    'Press through the feet and lift the hips without arching the lower back.',
    'از پاها فشار دهید و بدون قوس اضافی کمر، لگن را بالا بیاورید.',
    array['lower_back']),
  ('exercise:hip-hinge@v2', 'momentum-core@v2', 'hip-hinge', 'Hip hinge', 'خم شدن از لگن', 'hinge',
    'Push the hips back with a long spine, then return by squeezing the glutes.',
    'با ستون فقرات صاف لگن را عقب ببرید و با انقباض باسن برگردید.',
    array['lower_back']),
  ('exercise:dumbbell-rdl@v2', 'momentum-core@v2', 'dumbbell-rdl', 'Dumbbell Romanian deadlift', 'ددلیفت رومانیایی با دمبل', 'hinge',
    'Slide the dumbbells down the thighs by hinging at the hips, then stand tall.',
    'با خم شدن از لگن دمبل‌ها را روی ران پایین ببرید و صاف بایستید.',
    array['lower_back']),
  ('exercise:band-good-morning@v2', 'momentum-core@v2', 'band-good-morning', 'Band good morning', 'گود مورنینگ با کش', 'hinge',
    'Anchor a band, hinge with a braced torso, then return without rounding.',
    'کش را ثابت کنید، با تنه محکم خم شوید و بدون گرد شدن کمر برگردید.',
    array['lower_back']),
  ('exercise:wall-pushup@v2', 'momentum-core@v2', 'wall-pushup', 'Wall push-up', 'شنا روی دیوار', 'push',
    'Keep a straight body line, lower toward the wall, then press away with control.',
    'بدن را در یک خط نگه دارید، به دیوار نزدیک شوید و با کنترل فشار دهید.',
    array['shoulder', 'wrist']),
  ('exercise:knee-pushup@v2', 'momentum-core@v2', 'knee-pushup', 'Knee push-up', 'شنا روی زانو', 'push',
    'From the knees, lower the chest with elbows about 45 degrees, then press up.',
    'از روی زانو سینه را با آرنج حدود ۴۵ درجه پایین ببرید و بالا فشار دهید.',
    array['shoulder', 'wrist']),
  ('exercise:pushup@v2', 'momentum-core@v2', 'pushup', 'Push-up', 'شنا', 'push',
    'Hold a rigid line from head to heels, lower the chest, then press the floor away.',
    'بدن را از سر تا پاشنه صاف نگه دارید، سینه را پایین ببرید و از زمین فشار دهید.',
    array['shoulder', 'wrist']),
  ('exercise:dumbbell-press@v2', 'momentum-core@v2', 'dumbbell-press', 'Dumbbell overhead press', 'پرس سرشانه با دمبل', 'push',
    'Press the dumbbells overhead without shrugging, then lower to shoulder height.',
    'دمبل‌ها را بدون بالا انداختن شانه بالای سر ببرید و تا ارتفاع شانه پایین بیاورید.',
    array['shoulder']),
  ('exercise:band-chest-press@v2', 'momentum-core@v2', 'band-chest-press', 'Band chest press', 'پرس سینه با کش', 'push',
    'Press the handles forward at chest height without losing the ribcage position.',
    'دسته‌ها را در ارتفاع سینه به جلو فشار دهید و قفسه سینه را ثابت نگه دارید.',
    array['shoulder']),
  ('exercise:plank@v2', 'momentum-core@v2', 'plank', 'Plank', 'پلانک', 'push',
    'Brace the trunk, keep the hips level, and breathe without sagging or piking.',
    'تنه را محکم کنید، لگن را هم‌سطح نگه دارید و بدون افتادگی یا بالا رفتن لگن نفس بکشید.',
    array['lower_back', 'shoulder']),
  ('exercise:band-row@v2', 'momentum-core@v2', 'band-row', 'Band row', 'پارویی با کش', 'pull',
    'Pull the elbows back with a quiet neck, then return without rounding the shoulders.',
    'آرنج‌ها را با گردن آرام به عقب بکشید و بدون گرد شدن شانه برگردید.',
    array['shoulder']),
  ('exercise:dumbbell-row@v2', 'momentum-core@v2', 'dumbbell-row', 'Dumbbell row', 'پارویی با دمبل', 'pull',
    'Hinge, then row the dumbbell to the hip without twisting the torso.',
    'از لگن خم شوید و دمبل را بدون چرخش تنه تا کنار لگن بالا بکشید.',
    array['shoulder', 'lower_back']),
  ('exercise:band-pulldown@v2', 'momentum-core@v2', 'band-pulldown', 'Band pulldown', 'پول‌دان با کش', 'pull',
    'Pull the band toward the chest by driving the elbows down, then control the return.',
    'با هدایت آرنج به پایین کش را به سمت سینه بکشید و بازگشت را کنترل کنید.',
    array['shoulder']),
  ('exercise:reverse-fly@v2', 'momentum-core@v2', 'reverse-fly', 'Reverse fly', 'فلای معکوس', 'pull',
    'Hinge slightly and raise the arms out to the side without shrugging.',
    'کمی از لگن خم شوید و بازوها را بدون بالا انداختن شانه به طرفین بالا ببرید.',
    array['shoulder', 'neck']),
  ('exercise:band-pull-apart@v2', 'momentum-core@v2', 'band-pull-apart', 'Band pull-apart', 'باز کردن کش', 'pull',
    'Hold the band at chest height and pull it apart until the shoulder blades squeeze.',
    'کش را در ارتفاع سینه بگیرید و تا جمع شدن کتف‌ها از هم باز کنید.',
    array['shoulder']),
  ('exercise:suitcase-carry@v2', 'momentum-core@v2', 'suitcase-carry', 'Suitcase carry', 'حمل تک‌دست', 'carry',
    'Walk with one dumbbell at the side while keeping the ribs stacked over the pelvis.',
    'با یک دمبل در کنار بدن راه بروید و دنده‌ها را روی لگن نگه دارید.',
    array[]::text[]),
  ('exercise:farmer-carry@v2', 'momentum-core@v2', 'farmer-carry', 'Farmer carry', 'حمل کشاورز', 'carry',
    'Walk with a dumbbell in each hand, tall posture, and even steps.',
    'با دمبل در هر دست، قامت صاف و قدم‌های یکنواخت راه بروید.',
    array[]::text[]),
  ('exercise:goblet-carry@v2', 'momentum-core@v2', 'goblet-carry', 'Goblet carry', 'حمل گابلت', 'carry',
    'Hold a kettlebell at the chest and walk without leaning back.',
    'کتل‌بل را جلوی سینه بگیرید و بدون متمایل شدن به عقب راه بروید.',
    array[]::text[]),
  ('exercise:brisk-walk@v2', 'momentum-core@v2', 'brisk-walk', 'Brisk walk', 'پیاده‌روی تند', 'locomotion',
    'Walk at a pace that raises breathing while allowing short sentences.',
    'با سرعتی راه بروید که نفس را بالا ببرد ولی امکان گفتن جمله کوتاه باشد.',
    array['ankle']),
  ('exercise:march-in-place@v2', 'momentum-core@v2', 'march-in-place', 'March in place', 'قدم در جا', 'locomotion',
    'Lift the knees in place with an upright torso and relaxed arms.',
    'زانوها را در جا بالا بیاورید، تنه را صاف و بازوها را آرام نگه دارید.',
    array[]::text[]),
  ('exercise:step-up@v2', 'momentum-core@v2', 'step-up', 'Step-up', 'استپ‌آپ', 'locomotion',
    'Step onto a stable chair with the whole foot, then lower with control.',
    'با تمام پا روی صندلی پایدار بالا بروید و با کنترل پایین بیایید.',
    array['knee', 'ankle']),
  ('exercise:jump-rope@v2', 'momentum-core@v2', 'jump-rope', 'Jump rope', 'طناب‌زنی', 'locomotion',
    'Jump just high enough to clear the rope, landing softly on the midfoot.',
    'فقط به اندازه رد شدن طناب بپرید و نرم روی میانه پا فرود بیایید.',
    array['ankle', 'knee']),
  ('exercise:calf-raise@v2', 'momentum-core@v2', 'calf-raise', 'Calf raise', 'ساق پا', 'locomotion',
    'Rise onto the balls of the feet, pause, then lower without bouncing.',
    'روی سینه پا بالا بروید، مکث کنید و بدون جهش پایین بیایید.',
    array['ankle']),
  ('exercise:cat-cow@v2', 'momentum-core@v2', 'cat-cow', 'Cat cow', 'گربه و گاو', 'mobility',
    'Move slowly between rounding and arching the spine while breathing steadily.',
    'بین گرد کردن و قوس دادن ستون فقرات آرام حرکت کنید و یکنواخت نفس بکشید.',
    array['neck', 'lower_back']),
  ('exercise:hip-opener@v2', 'momentum-core@v2', 'hip-opener', 'Hip opener', 'بازکننده لگن', 'mobility',
    'Kneel into a gentle lunge and shift the hips forward without forcing the range.',
    'در یک لانج ملایم زانو بزنید و بدون اجبار، لگن را به جلو ببرید.',
    array['hip']),
  ('exercise:thoracic-rotation@v2', 'momentum-core@v2', 'thoracic-rotation', 'Thoracic rotation', 'چرخش قفسه سینه', 'mobility',
    'From all fours, rotate one arm toward the ceiling, then return with control.',
    'از حالت چهاردست‌وپا یک بازو را به سمت سقف بچرخانید و با کنترل برگردید.',
    array['shoulder', 'neck']),
  ('exercise:dead-bug@v2', 'momentum-core@v2', 'dead-bug', 'Dead bug', 'ددباگ', 'mobility',
    'Press the low back toward the floor and slowly extend opposite arm and leg.',
    'کمر را به زمین نزدیک کنید و دست و پای مخالف را آرام باز کنید.',
    array['lower_back']),
  ('exercise:bird-dog@v2', 'momentum-core@v2', 'bird-dog', 'Bird dog', 'برد داگ', 'mobility',
    'Reach opposite arm and leg without rotating the hips, then return to all fours.',
    'دست و پای مخالف را بدون چرخش لگن باز کنید و به چهاردست‌وپا برگردید.',
    array['lower_back']);

insert into public.exercise_equipment(exercise_id, equipment_id, required)
values
  ('exercise:sit-to-stand@v2', 'equipment:chair@v2', true),
  ('exercise:sit-to-stand@v2', 'equipment:bodyweight@v2', true),
  ('exercise:bodyweight-squat@v2', 'equipment:bodyweight@v2', true),
  ('exercise:goblet-squat@v2', 'equipment:dumbbells@v2', true),
  ('exercise:split-squat@v2', 'equipment:bodyweight@v2', true),
  ('exercise:glute-bridge@v2', 'equipment:yoga-mat@v2', true),
  ('exercise:glute-bridge@v2', 'equipment:bodyweight@v2', true),
  ('exercise:hip-hinge@v2', 'equipment:bodyweight@v2', true),
  ('exercise:dumbbell-rdl@v2', 'equipment:dumbbells@v2', true),
  ('exercise:band-good-morning@v2', 'equipment:resistance-band@v2', true),
  ('exercise:wall-pushup@v2', 'equipment:wall@v2', true),
  ('exercise:wall-pushup@v2', 'equipment:bodyweight@v2', true),
  ('exercise:knee-pushup@v2', 'equipment:yoga-mat@v2', true),
  ('exercise:knee-pushup@v2', 'equipment:bodyweight@v2', true),
  ('exercise:pushup@v2', 'equipment:yoga-mat@v2', true),
  ('exercise:pushup@v2', 'equipment:bodyweight@v2', true),
  ('exercise:dumbbell-press@v2', 'equipment:dumbbells@v2', true),
  ('exercise:band-chest-press@v2', 'equipment:resistance-band@v2', true),
  ('exercise:plank@v2', 'equipment:yoga-mat@v2', true),
  ('exercise:plank@v2', 'equipment:bodyweight@v2', true),
  ('exercise:band-row@v2', 'equipment:resistance-band@v2', true),
  ('exercise:dumbbell-row@v2', 'equipment:dumbbells@v2', true),
  ('exercise:band-pulldown@v2', 'equipment:resistance-band@v2', true),
  ('exercise:reverse-fly@v2', 'equipment:dumbbells@v2', true),
  ('exercise:band-pull-apart@v2', 'equipment:resistance-band@v2', true),
  ('exercise:suitcase-carry@v2', 'equipment:dumbbells@v2', true),
  ('exercise:farmer-carry@v2', 'equipment:dumbbells@v2', true),
  ('exercise:goblet-carry@v2', 'equipment:kettlebell@v2', true),
  ('exercise:brisk-walk@v2', 'equipment:bodyweight@v2', true),
  ('exercise:march-in-place@v2', 'equipment:bodyweight@v2', true),
  ('exercise:step-up@v2', 'equipment:chair@v2', true),
  ('exercise:jump-rope@v2', 'equipment:jump-rope@v2', true),
  ('exercise:calf-raise@v2', 'equipment:bodyweight@v2', true),
  ('exercise:cat-cow@v2', 'equipment:yoga-mat@v2', true),
  ('exercise:hip-opener@v2', 'equipment:yoga-mat@v2', true),
  ('exercise:thoracic-rotation@v2', 'equipment:yoga-mat@v2', true),
  ('exercise:dead-bug@v2', 'equipment:yoga-mat@v2', true),
  ('exercise:bird-dog@v2', 'equipment:yoga-mat@v2', true);

insert into public.exercise_substitutions(exercise_id, substitute_exercise_id, reason)
values
  ('exercise:sit-to-stand@v2', 'exercise:bodyweight-squat@v2', 'Standing squat option'),
  ('exercise:bodyweight-squat@v2', 'exercise:sit-to-stand@v2', 'Chair-supported squat option'),
  ('exercise:bodyweight-squat@v2', 'exercise:goblet-squat@v2', 'Loaded squat option'),
  ('exercise:goblet-squat@v2', 'exercise:bodyweight-squat@v2', 'Unload when equipment is unavailable'),
  ('exercise:split-squat@v2', 'exercise:sit-to-stand@v2', 'Lower-skill single-leg alternative'),
  ('exercise:sit-to-stand@v2', 'exercise:split-squat@v2', 'Split-stance progression'),
  ('exercise:glute-bridge@v2', 'exercise:hip-hinge@v2', 'Standing hinge option'),
  ('exercise:hip-hinge@v2', 'exercise:glute-bridge@v2', 'Supine posterior-chain option'),
  ('exercise:hip-hinge@v2', 'exercise:dumbbell-rdl@v2', 'Loaded hinge option'),
  ('exercise:dumbbell-rdl@v2', 'exercise:hip-hinge@v2', 'Unload the hinge'),
  ('exercise:band-good-morning@v2', 'exercise:glute-bridge@v2', 'Floor hinge when banding is unavailable'),
  ('exercise:glute-bridge@v2', 'exercise:band-good-morning@v2', 'Banded hinge option'),
  ('exercise:wall-pushup@v2', 'exercise:knee-pushup@v2', 'Progress the push pattern'),
  ('exercise:knee-pushup@v2', 'exercise:wall-pushup@v2', 'Reduce load on wrists and shoulders'),
  ('exercise:knee-pushup@v2', 'exercise:pushup@v2', 'Full push-up progression'),
  ('exercise:pushup@v2', 'exercise:knee-pushup@v2', 'Reduce load while keeping the pattern'),
  ('exercise:dumbbell-press@v2', 'exercise:band-chest-press@v2', 'Banded pressing option'),
  ('exercise:band-chest-press@v2', 'exercise:dumbbell-press@v2', 'Free-weight pressing option'),
  ('exercise:plank@v2', 'exercise:wall-pushup@v2', 'Lower-demand anterior-chain option'),
  ('exercise:wall-pushup@v2', 'exercise:plank@v2', 'Isometric trunk option'),
  ('exercise:band-row@v2', 'exercise:dumbbell-row@v2', 'Free-weight row option'),
  ('exercise:dumbbell-row@v2', 'exercise:band-row@v2', 'Banded row when dumbbells are unavailable'),
  ('exercise:band-pulldown@v2', 'exercise:band-row@v2', 'Horizontal pull substitute'),
  ('exercise:band-row@v2', 'exercise:band-pulldown@v2', 'Vertical pull option'),
  ('exercise:reverse-fly@v2', 'exercise:band-pull-apart@v2', 'Banded rear-delt option'),
  ('exercise:band-pull-apart@v2', 'exercise:reverse-fly@v2', 'Dumbbell rear-delt option'),
  ('exercise:suitcase-carry@v2', 'exercise:farmer-carry@v2', 'Bilateral carry option'),
  ('exercise:farmer-carry@v2', 'exercise:suitcase-carry@v2', 'Unilateral carry option'),
  ('exercise:farmer-carry@v2', 'exercise:goblet-carry@v2', 'Front-loaded carry option'),
  ('exercise:goblet-carry@v2', 'exercise:farmer-carry@v2', 'Side-loaded carry option'),
  ('exercise:brisk-walk@v2', 'exercise:march-in-place@v2', 'Indoor locomotion option'),
  ('exercise:march-in-place@v2', 'exercise:brisk-walk@v2', 'Outdoor walking option'),
  ('exercise:step-up@v2', 'exercise:sit-to-stand@v2', 'Lower-impact stepping option'),
  ('exercise:sit-to-stand@v2', 'exercise:step-up@v2', 'Stepping progression'),
  ('exercise:jump-rope@v2', 'exercise:brisk-walk@v2', 'Lower-impact cardio option'),
  ('exercise:brisk-walk@v2', 'exercise:jump-rope@v2', 'Higher-cadence cardio option'),
  ('exercise:calf-raise@v2', 'exercise:march-in-place@v2', 'Reduce Achilles demand'),
  ('exercise:march-in-place@v2', 'exercise:calf-raise@v2', 'Add ankle emphasis'),
  ('exercise:cat-cow@v2', 'exercise:thoracic-rotation@v2', 'Rotation-focused mobility'),
  ('exercise:thoracic-rotation@v2', 'exercise:cat-cow@v2', 'Sagittal spine mobility'),
  ('exercise:dead-bug@v2', 'exercise:bird-dog@v2', 'Quadruped core option'),
  ('exercise:bird-dog@v2', 'exercise:dead-bug@v2', 'Supine core option'),
  ('exercise:hip-opener@v2', 'exercise:glute-bridge@v2', 'Lower hip-flexion demand'),
  ('exercise:glute-bridge@v2', 'exercise:hip-opener@v2', 'Hip-mobility option');

commit;
